* Supervised Algorithm
* Predict continues information

In [1]:
import numpy as np

In [3]:
X = np.linspace(1,10,10000) #feature data
y = 2 * X + 5 #target data

In [4]:
X

array([  1.        ,   1.00090009,   1.00180018, ...,   9.99819982,
         9.99909991,  10.        ])

In [5]:
y

array([  7.        ,   7.00180018,   7.00360036, ...,  24.99639964,
        24.99819982,  25.        ])

In [6]:
from sklearn.linear_model import LinearRegression

In [7]:
model = LinearRegression()

In [8]:
model.fit(X.reshape(-1,1),y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [10]:
#Hyper-parameters - the initial params of machine learning models are known as hyper parameters
#By default hyper-parameters are set based on experiments

In [11]:
model.predict([[1.2]])

array([ 7.4])

In [12]:
model.coef_

array([ 2.])

In [13]:
model.intercept_

5.0

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
trainX, testX, trainy, testy = train_test_split(X,y)

In [18]:
model.fit(trainX.reshape(-1,1), trainy)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [20]:
model.score(testX.reshape(-1,1),testy)

1.0

In [ ]:
#### Polynomial degree

In [22]:
y = 2*X*X + 5*X + 10

In [23]:
model = LinearRegression()

In [24]:
from sklearn.preprocessing import PolynomialFeatures

In [25]:
pol = PolynomialFeatures(2)

In [27]:
X_new = pol.fit_transform(X.reshape(-1,1))

In [28]:
X_new

array([[   1.        ,    1.        ,    1.        ],
       [   1.        ,    1.00090009,    1.00180099],
       [   1.        ,    1.00180018,    1.0036036 ],
       ..., 
       [   1.        ,    9.99819982,   99.96399964],
       [   1.        ,    9.99909991,   99.98199901],
       [   1.        ,   10.        ,  100.        ]])

In [31]:
from sklearn.model_selection import train_test_split
trainX, testX, trainy, testy = train_test_split(X_new,y)

model.fit(trainX, trainy)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [32]:
model.coef_

array([ 0.,  5.,  2.])

In [33]:
model.intercept_

10.000000000000341

In [34]:
model.score(testX,testy)

1.0

In [35]:
### House Price Prediction

In [36]:
import pandas as pd

In [39]:
house_data = pd.read_csv('data/house_rental_data.csv',index_col='Unnamed: 0')

In [40]:
house_data.head()

Sqft  Floor  TotalFloor  Bedroom  Living.Room  Bathroom  Price
1  1177.698      2           7        2            2         2  62000
2  2134.800      5           7        4            2         2  78000
3  1138.560      5           7        2            2         1  58000
4  1458.780      2           7        3            2         2  45000
5   967.776     11          14        3            2         2  45000

In [41]:
house_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 645 entries, 1 to 648
Data columns (total 7 columns):
Sqft           645 non-null float64
Floor          645 non-null int64
TotalFloor     645 non-null int64
Bedroom        645 non-null int64
Living.Room    645 non-null int64
Bathroom       645 non-null int64
Price          645 non-null int64
dtypes: float64(1), int64(6)
memory usage: 40.3 KB


In [42]:
house_data.columns

Index(['Sqft', 'Floor', 'TotalFloor', 'Bedroom', 'Living.Room', 'Bathroom',
       'Price'],
      dtype='object')

In [43]:
feature_data = house_data[['Sqft', 'Floor', 'TotalFloor', 'Bedroom', 'Living.Room', 'Bathroom',]]
target_data = house_data['Price']

In [44]:
trainX, testX, trainy, testy = train_test_split(feature_data, target_data)

In [47]:
model = LinearRegression()

model.fit(trainX, trainy)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [48]:
model.score(testX,testy)

0.66610236156084779

In [60]:
pol = PolynomialFeatures(2)
feature_data_deg2 = pol.fit_transform(feature_data)

In [61]:
feature_data_deg2.shape

(645, 84)

In [57]:
model = LinearRegression()
trainX, testX, trainy, testy = train_test_split(feature_data_deg2, target_data)

In [58]:
model.fit(trainX,trainy)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [59]:
model.score(testX,testy)

0.58884489642675908

In [62]:
### Degree 3

In [63]:
pol = PolynomialFeatures(3)
feature_data_deg3 = pol.fit_transform(feature_data)

In [64]:
model = LinearRegression()
trainX, testX, trainy, testy = train_test_split(feature_data_deg3, target_data)

In [65]:
model.fit(trainX,trainy)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [66]:
model.score(testX,testy)

-0.4435917458671032