In [4]:
import numpy as np
 
def sigmoid(inputs):
    """
    Calculate the sigmoid for the give inputs (array)
    :param inputs:
    :return:
    """
    sigmoid_scores = [1 / float(1 + np.exp(- x)) for x in inputs]
    return sigmoid_scores
 
 
sigmoid_inputs = [-1, 2, 3, 5, 6999]
print ("Sigmoid Function Output :: {}".format(sigmoid(sigmoid_inputs)))

Sigmoid Function Output :: [0.2689414213699951, 0.8807970779778823, 0.9525741268224334, 0.9933071490757153, 1.0]


In [5]:
from sklearn.linear_model import LogisticRegression

In [6]:
lr = LogisticRegression()

In [12]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split

In [9]:
cancer_data = load_breast_cancer()

In [11]:
cancer_data.data.shape

(569, 30)

In [13]:
trainX, testX, trainY, testY = train_test_split(cancer_data.data, cancer_data.target)

In [14]:
lr.fit(trainX, trainY)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [15]:
lr.score(testX, testY)

0.95804195804195802

In [16]:
lr.predict_proba(testX[:6])

array([[  6.31038840e-03,   9.93689612e-01],
       [  8.70210250e-02,   9.12978975e-01],
       [  9.99999998e-01,   1.84658362e-09],
       [  5.17161347e-02,   9.48283865e-01],
       [  3.45026504e-03,   9.96549735e-01],
       [  1.00000000e+00,   4.83563156e-16]])

In [17]:
lr.predict(testX[:5])

array([1, 1, 0, 1, 1])

In [18]:
testX[:5]

array([[  1.41100000e+01,   1.28800000e+01,   9.00300000e+01,
          6.16500000e+02,   9.30900000e-02,   5.30600000e-02,
          1.76500000e-02,   2.73300000e-02,   1.37300000e-01,
          5.70000000e-02,   2.57100000e-01,   1.08100000e+00,
          1.55800000e+00,   2.39200000e+01,   6.69200000e-03,
          1.13200000e-02,   5.71700000e-03,   6.62700000e-03,
          1.41600000e-02,   2.47600000e-03,   1.55300000e+01,
          1.80000000e+01,   9.84000000e+01,   7.49900000e+02,
          1.28100000e-01,   1.10900000e-01,   5.30700000e-02,
          5.89000000e-02,   2.10000000e-01,   7.08300000e-02],
       [  1.57100000e+01,   1.39300000e+01,   1.02000000e+02,
          7.61700000e+02,   9.46200000e-02,   9.46200000e-02,
          7.13500000e-02,   5.93300000e-02,   1.81600000e-01,
          5.72300000e-02,   3.11700000e-01,   8.15500000e-01,
          1.97200000e+00,   2.79400000e+01,   5.21700000e-03,
          1.51500000e-02,   1.67800000e-02,   1.26800000e-02,
       

In [19]:
import pandas as pd

In [21]:
hr_data = pd.read_csv('HR_comma_sep.csv')

In [22]:
hr_data.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  left  promotion_last_5years  sales  \
0                   3              0     1                      0  sales   
1                   6              0     1                      0  sales   
2                   4              0     1                      0  sales   
3                   5              0     1                      0  sales   
4                   3              0     1                      0  sales   

   salary  
0     low  
1  medium  
2  medium  
3     low  
4     low

In [23]:
hr_data.sales.unique()

array(['sales', 'accounting', 'hr', 'technical', 'support', 'management',
       'IT', 'product_mng', 'marketing', 'RandD'], dtype=object)

In [25]:
hr_data.salary.unique()

array(['low', 'medium', 'high'], dtype=object)

In [27]:
from sklearn.preprocessing import LabelEncoder

In [28]:
le = LabelEncoder()

In [29]:
hr_data['sales'] = le.fit_transform(hr_data.sales)
hr_data['salary'] = le.fit_transform(hr_data.salary)

In [33]:
f = hr_data.corr()['left']

In [42]:
imp_features = np.abs(f).sort_values(ascending=False).index.tolist()[1:5]

In [44]:
trainX, testX, trainY, testY = train_test_split(hr_data[imp_features], hr_data['left'])

In [45]:
lr = LogisticRegression()

In [46]:
lr.fit(trainX, trainY)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [47]:
lr.score(testX, testY)

0.77306666666666668

In [48]:
imp_features

['satisfaction_level',
 'Work_accident',
 'time_spend_company',
 'average_montly_hours']

In [49]:
trainX[:5]

satisfaction_level  Work_accident  time_spend_company  \
4743                 0.78              0                   3   
11742                0.92              0                   8   
5531                 0.53              0                   4   
5763                 0.96              0                   3   
6754                 0.89              0                   3   

       average_montly_hours  
4743                    257  
11742                   143  
5531                    143  
5763                    230  
6754                    252

In [50]:
lr.predict([[0.78,0,3,257]])

array([0], dtype=int64)

In [51]:
trainY[:5]

4743     0
11742    0
5531     0
5763     0
6754     0
Name: left, dtype: int64