In [1]:
import pandas as pd

In [2]:
import os

In [3]:
images = os.listdir('data/dog-train/')
os.chdir('data/dog-train/')

In [4]:
from skimage.transform import resize
from skimage.io import imsave, imread


In [5]:
for img_name in images:
    img = imread(img_name)
    img_new = resize(img, (128,128))
    imsave('n_' +img_name, img_new)

C:\Users\ZekeLabs\Anaconda3-N\lib\site-packages\skimage\transform\_warps.py:84: UserWarning: The default mode, 'constant', will be changed to 'reflect' in skimage 0.15.
  warn("The default mode, 'constant', will be changed to 'reflect' in "
C:\Users\ZekeLabs\Anaconda3-N\lib\site-packages\skimage\util\dtype.py:122: UserWarning: Possible precision loss when converting from float64 to uint8
  .format(dtypeobj_in, dtypeobj_out))


In [6]:
imgs = os.listdir('.')

In [40]:

img_ids = []
img_v =[]
for img in imgs:
    v = imread(img)
    img_id = img.replace('n_','').replace('.jpg','')
    img_ids.append(img_id)
    img_v.append(v.ravel())

In [8]:
df_img = pd.DataFrame({'id':img_ids,'v':img_v})

In [9]:
df_label = pd.read_csv(r'D:/machine-learning-for-beginners/data/train/labels.csv')

In [10]:
final_df = pd.merge(left=df_img, right=df_label)

In [11]:
final_df.drop('id', axis=1, inplace=True)

In [12]:
data = final_df.v

In [109]:
data

0     [173, 122, 93, 136, 89, 45, 211, 171, 109, 158...
1     [173, 122, 93, 136, 89, 45, 211, 171, 109, 158...
2     [0, 4, 0, 6, 17, 11, 8, 19, 13, 10, 19, 14, 19...
3     [0, 4, 0, 6, 17, 11, 8, 19, 13, 10, 19, 14, 19...
4     [130, 65, 69, 177, 116, 121, 147, 92, 95, 172,...
5     [130, 65, 69, 177, 116, 121, 147, 92, 95, 172,...
6     [74, 83, 78, 74, 83, 78, 75, 84, 79, 76, 85, 8...
7     [74, 83, 78, 74, 83, 78, 75, 84, 79, 76, 85, 8...
8     [162, 176, 163, 212, 226, 213, 225, 238, 228, ...
9     [161, 175, 162, 212, 226, 213, 226, 239, 229, ...
10    [219, 108, 114, 229, 118, 124, 220, 113, 119, ...
11    [219, 108, 114, 229, 118, 124, 220, 113, 119, ...
12    [13, 25, 11, 0, 11, 0, 8, 19, 5, 17, 25, 14, 0...
13    [13, 25, 11, 0, 11, 0, 8, 19, 5, 17, 25, 14, 0...
14    [176, 118, 81, 166, 110, 73, 174, 120, 82, 192...
15    [176, 118, 81, 166, 110, 73, 174, 120, 82, 191...
16    [90, 123, 42, 89, 122, 41, 88, 123, 43, 88, 12...
17    [90, 123, 42, 89, 122, 41, 88, 123, 43, 88

In [104]:
d = data.as_matrix()
n = data[0]

In [105]:
for e in d[1]:
    n = np.hstack((n,e))

In [110]:
d

array([array([173, 122,  93, ..., 181, 138,  93], dtype=uint8),
       array([173, 122,  93, ..., 181, 138,  93], dtype=uint8),
       array([ 0,  4,  0, ..., 10, 32, 20], dtype=uint8),
       array([ 0,  4,  0, ..., 10, 32, 20], dtype=uint8),
       array([130,  65,  69, ..., 204, 203, 201], dtype=uint8),
       array([130,  65,  69, ..., 204, 203, 201], dtype=uint8),
       array([ 74,  83,  78, ..., 255, 255, 255], dtype=uint8),
       array([ 74,  83,  78, ..., 255, 255, 255], dtype=uint8),
       array([162, 176, 163, ..., 204, 209, 215], dtype=uint8),
       array([161, 175, 162, ..., 204, 209, 215], dtype=uint8),
       array([219, 108, 114, ...,  89, 118, 150], dtype=uint8),
       array([219, 108, 114, ...,  89, 118, 150], dtype=uint8),
       array([ 13,  25,  11, ..., 141, 124, 106], dtype=uint8),
       array([ 13,  25,  11, ..., 141, 124, 106], dtype=uint8),
       array([176, 118,  81, ...,  78,  36,  20], dtype=uint8),
       array([176, 118,  81, ...,  78,  36,  20], dt

In [92]:
n

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [95]:
n

array([  0.,   0.,   0., ...,   7.,  18.,  22.])

In [100]:
d = n.reshape(25,-1)

In [101]:
d.shape

(25, 49152)

In [103]:
final_df.breed

0                 boston_bull
1                 boston_bull
2                       dingo
3                       dingo
4            golden_retriever
5            golden_retriever
6          standard_schnauzer
7          standard_schnauzer
8         irish_water_spaniel
9         irish_water_spaniel
10    black-and-tan_coonhound
11    black-and-tan_coonhound
12                      cairn
13                      cairn
14              affenpinscher
15              affenpinscher
16         labrador_retriever
17         labrador_retriever
18               ibizan_hound
19               ibizan_hound
20             english_setter
21             english_setter
22               walker_hound
23               walker_hound
Name: breed, dtype: object