In [1]:
import numpy as np

In [2]:
a = np.random.randint(1,10,size=(5,5))

In [3]:
a

array([[1, 2, 6, 1, 4],
       [1, 7, 1, 6, 1],
       [8, 3, 2, 3, 8],
       [5, 1, 4, 5, 1],
       [1, 5, 7, 1, 1]])

In [5]:
a.reshape(25,1).shape

(25, 1)

In [6]:
a.size

25

In [7]:
a.ndim

2

In [8]:
a = np.random.randint(1,10,size=(4,6))

In [9]:
a

array([[8, 3, 5, 9, 2, 3],
       [8, 6, 2, 6, 2, 7],
       [6, 7, 7, 9, 8, 3],
       [9, 7, 2, 6, 1, 9]])

In [10]:
a.reshape(12,2)

array([[8, 3],
       [5, 9],
       [2, 3],
       [8, 6],
       [2, 6],
       [2, 7],
       [6, 7],
       [7, 9],
       [8, 3],
       [9, 7],
       [2, 6],
       [1, 9]])

In [11]:
a.reshape(-1,3)

array([[8, 3, 5],
       [9, 2, 3],
       [8, 6, 2],
       [6, 2, 7],
       [6, 7, 7],
       [9, 8, 3],
       [9, 7, 2],
       [6, 1, 9]])

In [13]:
a.reshape(1,-1)

array([[8, 3, 5, 9, 2, 3, 8, 6, 2, 6, 2, 7, 6, 7, 7, 9, 8, 3, 9, 7, 2, 6,
        1, 9]])

In [14]:
a = np.random.randint(1,10,size=(6,6))

In [19]:
x,y,z = np.hsplit(a,[3,5])

In [17]:
a

array([[2, 4, 5, 1, 4, 2],
       [3, 7, 7, 5, 6, 8],
       [2, 9, 3, 7, 8, 7],
       [7, 9, 6, 3, 3, 6],
       [8, 4, 5, 4, 2, 5],
       [5, 5, 1, 4, 5, 8]])

In [20]:
x

array([[2, 4, 5],
       [3, 7, 7],
       [2, 9, 3],
       [7, 9, 6],
       [8, 4, 5],
       [5, 5, 1]])

In [21]:
y

array([[1, 4],
       [5, 6],
       [7, 8],
       [3, 3],
       [4, 2],
       [4, 5]])

In [22]:
z

array([[2],
       [8],
       [7],
       [6],
       [5],
       [8]])

In [23]:
a

array([[2, 4, 5, 1, 4, 2],
       [3, 7, 7, 5, 6, 8],
       [2, 9, 3, 7, 8, 7],
       [7, 9, 6, 3, 3, 6],
       [8, 4, 5, 4, 2, 5],
       [5, 5, 1, 4, 5, 8]])

In [26]:
x,y,z = np.vsplit(a,[2,4])

In [27]:
x

array([[2, 4, 5, 1, 4, 2],
       [3, 7, 7, 5, 6, 8]])

In [28]:
y

array([[2, 9, 3, 7, 8, 7],
       [7, 9, 6, 3, 3, 6]])

In [29]:
z

array([[8, 4, 5, 4, 2, 5],
       [5, 5, 1, 4, 5, 8]])

In [30]:
a

array([[2, 4, 5, 1, 4, 2],
       [3, 7, 7, 5, 6, 8],
       [2, 9, 3, 7, 8, 7],
       [7, 9, 6, 3, 3, 6],
       [8, 4, 5, 4, 2, 5],
       [5, 5, 1, 4, 5, 8]])

In [31]:
np.vstack([a,a])

array([[2, 4, 5, 1, 4, 2],
       [3, 7, 7, 5, 6, 8],
       [2, 9, 3, 7, 8, 7],
       [7, 9, 6, 3, 3, 6],
       [8, 4, 5, 4, 2, 5],
       [5, 5, 1, 4, 5, 8],
       [2, 4, 5, 1, 4, 2],
       [3, 7, 7, 5, 6, 8],
       [2, 9, 3, 7, 8, 7],
       [7, 9, 6, 3, 3, 6],
       [8, 4, 5, 4, 2, 5],
       [5, 5, 1, 4, 5, 8]])

In [32]:
np.hstack([a,a])

array([[2, 4, 5, 1, 4, 2, 2, 4, 5, 1, 4, 2],
       [3, 7, 7, 5, 6, 8, 3, 7, 7, 5, 6, 8],
       [2, 9, 3, 7, 8, 7, 2, 9, 3, 7, 8, 7],
       [7, 9, 6, 3, 3, 6, 7, 9, 6, 3, 3, 6],
       [8, 4, 5, 4, 2, 5, 8, 4, 5, 4, 2, 5],
       [5, 5, 1, 4, 5, 8, 5, 5, 1, 4, 5, 8]])