In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])

In [3]:
a

array([1, 2, 3, 4])

In [5]:
a = np.zeros((3,3))

In [6]:
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
a = np.ones((3,3))

In [8]:
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
np.full((3,3),44)

array([[44, 44, 44],
       [44, 44, 44],
       [44, 44, 44]])

In [10]:
np.full((3,3),'hello')

array([['hello', 'hello', 'hello'],
       ['hello', 'hello', 'hello'],
       ['hello', 'hello', 'hello']], dtype='<U5')

In [11]:
a = np.array(['abc','def','abcdef'])

In [12]:
a

array(['abc', 'def', 'abcdef'], dtype='<U6')

In [13]:
a[0] = 'abcdefghi'

In [14]:
a

array(['abcdef', 'def', 'abcdef'], dtype='<U6')

In [15]:
np.random.randint(1,10,size=(3,4,5))

array([[[6, 7, 9, 2, 6],
        [8, 3, 3, 8, 6],
        [9, 3, 3, 5, 3],
        [2, 1, 4, 3, 9]],

       [[9, 9, 5, 1, 3],
        [6, 9, 4, 4, 1],
        [7, 3, 9, 6, 9],
        [8, 9, 7, 9, 4]],

       [[2, 5, 2, 4, 4],
        [8, 9, 7, 2, 4],
        [6, 9, 6, 1, 1],
        [5, 9, 1, 8, 5]]])

In [19]:
np.random.rand()

0.31714367148907974

In [30]:
a = np.linspace(1,10,100)

In [32]:
a[:10]

array([1.        , 1.09090909, 1.18181818, 1.27272727, 1.36363636,
       1.45454545, 1.54545455, 1.63636364, 1.72727273, 1.81818182])

In [33]:
a[10:15]

array([1.90909091, 2.        , 2.09090909, 2.18181818, 2.27272727])

In [34]:
data = np.random.randint(1,10,size=(5,5))

In [35]:
data

array([[6, 6, 4, 7, 6],
       [4, 8, 3, 5, 3],
       [5, 8, 4, 6, 1],
       [5, 7, 6, 5, 8],
       [4, 8, 4, 3, 8]])

In [40]:
data[:,2]

array([4, 3, 4, 6, 4])

In [41]:
data[2:4]

array([[5, 8, 4, 6, 1],
       [5, 7, 6, 5, 8]])

In [43]:
data[3:]

array([[5, 7, 6, 5, 8],
       [4, 8, 4, 3, 8]])