In [9]:
from sklearn.feature_extraction import DictVectorizer

In [10]:
# One-hot encoding
one_hot_encoder = DictVectorizer()

In [11]:
instances = [ {'city':'Bangalore'}, {'city':'Tezpur'}, {'city':'Chennai'}, {'city':'Mumbai'}, {'city':'Allahabad'}, {'city':'Mangalore'}]

In [12]:
encoder = one_hot_encoder.fit_transform(instances)


In [13]:
# It creates coloumn for each possible options
# Allahabad -> 1, Bangalore -> 2, Chennai -> 3, Mangalore -> 4, Mumbai -> 5 Tezpur -> 6, 
print encoder.toarray()

[[ 0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.]
 [ 0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.]
 [ 1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.]]


### Bag-of-words

This representation uses a multiset, or bag, that encodes the words that appear in a text; the bag-of-words does not encode any of the text's syntax, ignores the order of words, and disregards all grammar.
One important understanding here is - text with similar words will have similar meaning

In [14]:
from sklearn.feature_extraction.text import CountVectorizer

In [15]:
corpus = [
'UNC played Duke in basketball',
'Duke lost the basketball game',
'I ate a sandwich'
]

In [16]:
vectorizer = CountVectorizer()

In [17]:
counts = vectorizer.fit_transform(corpus).todense()
print counts

[[0 1 1 0 1 0 1 0 0 1]
 [0 1 1 1 0 1 0 0 1 0]
 [1 0 0 0 0 0 0 1 0 0]]


In [18]:
print vectorizer.vocabulary_

{u'duke': 2, u'basketball': 1, u'lost': 5, u'played': 6, u'in': 4, u'game': 3, u'sandwich': 7, u'unc': 9, u'ate': 0, u'the': 8}


In [19]:
from sklearn.metrics.pairwise import euclidean_distances
# Lesser eucliden_distance mean they are similar

In [20]:
euclidean_distances(counts[0], counts[1])

array([[ 2.44948974]])

In [21]:
euclidean_distances(counts[1], counts[2])

array([[ 2.64575131]])

In [22]:
euclidean_distances(counts[0], counts[2])

array([[ 2.64575131]])

# Stop Words

In [23]:
vectorizer = CountVectorizer(stop_words='english')

In [24]:
print vectorizer.fit_transform(corpus).todense()

[[0 1 1 0 0 1 0 1]
 [0 1 1 1 1 0 0 0]
 [1 0 0 0 0 0 1 0]]


In [25]:
print vectorizer.vocabulary_

{u'duke': 2, u'basketball': 1, u'lost': 4, u'played': 5, u'game': 3, u'sandwich': 6, u'unc': 7, u'ate': 0}


# Problems with this 

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
corpus = [
'He ate the sandwiches',
'Every sandwich was eaten by him'
]
vectorizer = CountVectorizer(binary=True, stop_words='english')
print vectorizer.fit_transform(corpus).todense()
print vectorizer.vocabulary_

[[1 0 0 1]
 [0 1 1 0]]
{u'sandwich': 2, u'ate': 0, u'sandwiches': 3, u'eaten': 1}


# Stemming and lemmatization 

In [ ]:
import nltk
nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


In [ ]:
from nltk.stem.wordnet import WordNetLemmatizer

In [ ]:
lemmatizer = WordNetLemmatizer()
print lemmatizer.lemmatize('gathering', 'v')
print lemmatizer.lemmatize('gathering', 'n')

In [ ]:
from nltk.stem import PorterStemmer
stemmer = PorterStemmer()
print stemmer.stem('gathering')

# Lemmatize our test case

In [27]:
from nltk import word_tokenize
from nltk.stem import PorterStemmer
from nltk.stem.wordnet import WordNetLemmatizer

wordnet_tags = ['n', 'v']
corpus = [
'He ate the sandwiches',
'Everydays sandwich was eaten by him gooder nicee nicer'
]

In [28]:
# Stemming the corpus
stemmer = PorterStemmer()
print 'Stemmed:', [[stemmer.stem(token) for token in word_tokenize(document)] for document in corpus]

Stemmed: [[u'He', u'ate', u'the', u'sandwich'], [u'Everyday', u'sandwich', u'wa', u'eaten', u'by', u'him', u'gooder', u'nice', u'nicer']]


In [3]:
def lemmatize(token, tag):
    if tag[0].lower() in ['n', 'v']:
        return lemmatizer.lemmatize(token, tag[0].lower())
    return token

lemmatizer = WordNetLemmatizer()

In [16]:
help(pos_tag)

Help on function pos_tag in module nltk.tag:

pos_tag(tokens, tagset=None)
    Use NLTK's currently recommended part of speech tagger to
    tag the given list of tokens.
    
        >>> from nltk.tag import pos_tag
        >>> from nltk.tokenize import word_tokenize
        >>> pos_tag(word_tokenize("John's big idea isn't all that bad."))
        [('John', 'NNP'), ("'s", 'POS'), ('big', 'JJ'), ('idea', 'NN'), ('is', 'VBZ'),
        ("n't", 'RB'), ('all', 'PDT'), ('that', 'DT'), ('bad', 'JJ'), ('.', '.')]
        >>> pos_tag(word_tokenize("John's big idea isn't all that bad."), tagset='universal')
        [('John', 'NOUN'), ("'s", 'PRT'), ('big', 'ADJ'), ('idea', 'NOUN'), ('is', 'VERB'),
        ("n't", 'ADV'), ('all', 'DET'), ('that', 'DET'), ('bad', 'ADJ'), ('.', '.')]
    
    NB. Use `pos_tag_sents()` for efficient tagging of more than one sentence.
    
    :param tokens: Sequence of tokens to be tagged
    :type tokens: list(str)
    :param tagset: the tagset to be used, e.g. un

In [5]:
#Sentence Toekenizer
text = "this's a sent tokenize test. this is sent two. is this sent three? sent 4 is cool! Now it's your turn."
from nltk.tokenize import sent_tokenize
sent_tokenize_list = sent_tokenize(text)
print len(sent_tokenize_list)
print sent_tokenize_list

5
["this's a sent tokenize test.", 'this is sent two.', 'is this sent three?', 'sent 4 is cool!', "Now it's your turn."]


In [6]:
#Word Tokenizer
from nltk.tokenize import word_tokenize
print word_tokenize('Hello World.')
print word_tokenize("this's a test")

['Hello', 'World', '.']
['this', "'s", 'a', 'test']


In [ ]:
words = word_tokenize("Dive into NLTK: Part-of-speech tagging and POS Tagger")
import nltk
print nltk.pos_tag(words)