In [1]:
import numpy as np

In [2]:
X = np.linspace(1,100,1000)

In [3]:
Y = 2*X*X + 5*X + 10

In [4]:
import pandas as pd

In [5]:
df = pd.DataFrame({'X':X,'Y':Y})

In [7]:
df.head()

X          Y
0  1.000000  17.000000
1  1.099099  17.911533
2  1.198198  18.862349
3  1.297297  19.852447
4  1.396396  20.881828

In [8]:
from sklearn.model_selection import train_test_split

In [16]:
trainX, testX, trainY, testY = train_test_split(df[['X']], df.Y)

In [17]:
trainX.count()

X    750
dtype: int64

In [18]:
testX.count()

X    250
dtype: int64

In [19]:
from sklearn.preprocessing import PolynomialFeatures

In [26]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [31]:
models = []
transformers = []
for i in range(1,4):
    pol = PolynomialFeatures(i)
    pol.fit(df[['X']])
    transformers.append(pol)
    X_tf = pol.transform(df[['X']])
    trainX, testX, trainY, testY = train_test_split(X_tf,df.Y)
    lr = LinearRegression()
    lr.fit(trainX,trainY)
    models.append(lr)
    y_pred = lr.predict(testX)
    print (mean_squared_error(y_pred=y_pred, y_true=testY))

1868960.31063
2.58623890164e-24
5.44921838345e-20


In [42]:
data = [[150],[152]]

In [44]:
data_tf = transformers[1].transform(data)

In [45]:
models[1].predict(data_tf)

array([ 45760.,  46978.])

In [46]:
2*150*150 + 5*150 + 10

45760

In [47]:
models[1].coef_

array([ 0.,  5.,  2.])

In [48]:
models[1].intercept_

10.000000000001819

In [50]:
models[2].coef_

array([  0.00000000e+00,   5.00000000e+00,   2.00000000e+00,
         8.88178420e-16])

In [ ]:
from sklearn.linear_model import LogisticRegressionCV