In [2]:
import numpy as np

In [3]:
X = np.linspace(1,100,10000)

In [5]:
Y = 2 * X * X + 5 * X + 101

In [6]:
import pandas as pd

In [8]:
df = pd.DataFrame({'X':X, 'Y':Y})

In [9]:
df.head()

X           Y
0  1.000000  103.000000
1  1.009901  103.019802
2  1.019802  103.039604
3  1.029703  103.059406
4  1.039604  103.079208

In [10]:
from sklearn.linear_model import LinearRegression

In [11]:
lr = LinearRegression()

In [13]:
lr.fit(df.iloc[5:][['X']], df.iloc[5:]['Y'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [14]:
df.head()

X           Y
0  1.000000  103.000000
1  1.009901  103.019802
2  1.019802  103.039604
3  1.029703  103.059406
4  1.039604  103.079208

In [17]:
lr.predict(df[:5][['X']])

array([ 103.        ,  103.01980198,  103.03960396,  103.05940594,
        103.07920792])

In [18]:
lr.coef_

array([ 2.])

In [19]:
lr.intercept_

100.99999999999997

In [20]:
lr.predict([[10001],[10004]])

array([ 20103.,  20109.])