In [2]:
from sklearn.datasets import make_regression

In [7]:
X,Y = make_regression(n_features=2,n_samples=1000)

In [8]:
X

array([[ 1.67854266, -0.15680396],
       [ 0.80042281,  1.431742  ],
       [-0.41733404, -1.01649677],
       ...,
       [ 0.03938298, -2.04383373],
       [-1.47373285, -0.3086885 ],
       [-0.12342629, -0.07633357]])

In [9]:
import numpy as np

In [10]:
X = np.linspace(1,10,1000)

In [12]:
Y = 5*X + 44

In [15]:
from sklearn.linear_model import LinearRegression

In [16]:
lr = LinearRegression()

In [20]:
feature_data = X[:-5].reshape(-1,1)

In [21]:
target_data = Y[:-5]

In [22]:
lr.fit(feature_data,target_data)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [23]:
lr.predict(X[-5:].reshape(-1,1))

array([93.81981982, 93.86486486, 93.90990991, 93.95495495, 94.        ])

In [24]:
Y[-5:]

array([93.81981982, 93.86486486, 93.90990991, 93.95495495, 94.        ])

In [25]:
lr.coef_

array([5.])

In [26]:
lr.intercept_

44.000000000000014

In [27]:
X[-5:]

array([ 9.96396396,  9.97297297,  9.98198198,  9.99099099, 10.        ])

In [ ]:
5 * 9.96 + 44