In [1]:
import numpy as np

In [25]:
X = np.linspace(0,1,10000)

In [26]:
Y = 12*X*X*X + 5*X + 100

In [27]:
X

array([0.00000000e+00, 1.00010001e-04, 2.00020002e-04, ...,
       9.99799980e-01, 9.99899990e-01, 1.00000000e+00])

In [24]:
Y

array([[117.        , 100.        , 100.        ],
       [117.        , 100.00050005, 100.00000005],
       [117.        , 100.0010001 , 100.0000002 ],
       ...,
       [117.        , 116.99180062, 116.98360576],
       [117.        , 116.99589995, 116.99180103],
       [117.        , 117.        , 117.        ]])

In [28]:
from sklearn.preprocessing import PolynomialFeatures

In [29]:
pol = PolynomialFeatures(2)

In [30]:
X = pol.fit_transform(X.reshape(-1,1))

In [31]:
t = np.arange(10).reshape(-1,1)
t

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [32]:
pol.fit_transform(t)

array([[ 1.,  0.,  0.],
       [ 1.,  1.,  1.],
       [ 1.,  2.,  4.],
       [ 1.,  3.,  9.],
       [ 1.,  4., 16.],
       [ 1.,  5., 25.],
       [ 1.,  6., 36.],
       [ 1.,  7., 49.],
       [ 1.,  8., 64.],
       [ 1.,  9., 81.]])

In [33]:
from sklearn.linear_model import LinearRegression

In [34]:
lr = LinearRegression()

In [39]:
lr.fit(X[:-100],Y[:-100])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [40]:
lr.coef_

array([ 0.        , -2.05634933, 17.819982  ])

In [41]:
lr.intercept_

100.58200121224063

In [42]:
from sklearn.metrics import mean_absolute_error

In [48]:
y_pred = lr.predict(X[-100:])

In [49]:
mean_absolute_error(Y[-100:],y_pred)

0.618245461091569

In [50]:
pol = PolynomialFeatures(3)

In [51]:
X = np.linspace(0,1,10000)

In [52]:
X = pol.fit_transform(X.reshape(-1,1))

In [54]:
X.shape

(10000, 4)

In [55]:
lr = LinearRegression()
lr.fit(X[:-100],Y[:-100])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [56]:
y_pred = lr.predict(X[-100:])

In [57]:
mean_absolute_error(Y[-100:],y_pred)

1.2647660696529783e-14