In [1]:
import numpy as np

In [2]:
X = np.linspace(1,10,1000)

In [3]:
Y = 2 * X + 10

In [6]:
from sklearn.linear_model import LinearRegression 

In [7]:
lr = LinearRegression()

In [8]:
lr.fit(X.reshape(-1,1),Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [9]:
lr.coef_

array([2.])

In [10]:
lr.intercept_

10.000000000000005

In [12]:
lr.predict(X[:2].reshape(-1,1))

array([12.        , 12.01801802])

In [13]:
Y[:2]

array([12.        , 12.01801802])

In [17]:
lr.coef_[0] * 1 + lr.intercept_

12.000000000000004

In [16]:
X[:2]

array([1.        , 1.00900901])