In [1]:
import numpy as np

In [2]:
X = np.linspace(1,100,10000)

In [3]:
Y = 2*X*X + 3*X + 55

In [4]:
import pandas as pd

In [5]:
df = pd.DataFrame({'X':X, 'Y':Y})

In [7]:
df.head()

X          Y
0  1.000000  60.000000
1  1.009901  60.069503
2  1.019802  60.139398
3  1.029703  60.209685
4  1.039604  60.280365

In [8]:
from sklearn.model_selection import train_test_split

In [13]:
from sklearn.linear_model import LinearRegression

In [10]:
from sklearn.preprocessing import PolynomialFeatures

In [16]:
models = []
for degree in range(1,5):
    pol = PolynomialFeatures(degree)
    X_tf = pol.fit_transform(df[['X']])
    trainX, testX, trainY, testY = train_test_split(X_tf, df.Y)
    lr = LinearRegression()
    lr.fit(trainX, trainY)
    models.append(lr)
    print (degree, lr.score(testX,testY))

1 0.943090527575
2 1.0
3 1.0
4 1.0


In [18]:
models[0].coef_

array([   0.        ,  203.93046111])

In [20]:
models[1].coef_

array([ 0.,  3.,  2.])

In [21]:
models[1].intercept_

55.000000000010004

In [22]:
from sklearn.datasets import california_housing

In [23]:
housing_data = california_housing.fetch_california_housing()

In [25]:
housing_data.target

array([ 4.526,  3.585,  3.521, ...,  0.923,  0.847,  0.894])

In [27]:
from sklearn.metrics import mean_squared_error

In [35]:
models = []
transformers = []
for degree in range(1,5):
    pol = PolynomialFeatures(degree)
    pol.fit(housing_data.data)
    X_tf = pol.transform(housing_data.data)
    trainX, testX, trainY, testY = train_test_split(X_tf, housing_data.target)
    lr = LinearRegression()
    lr.fit(trainX, trainY)
    models.append(lr)
    transformers.append(pol)
    y_pred = lr.predict(testX)
    print (degree, mean_squared_error(y_pred=y_pred, y_true=testY))

1 0.540557773491
2 5.25587589933
3 7.44147210138
4 1766835.86803


In [32]:
housing_data.data[:2].shape

(2, 8)

In [36]:
tf_data = transformers[0].transform(housing_data.data[:3])

In [37]:
models[0].predict(tf_data)

array([ 4.13218567,  3.98747961,  3.67191709])

In [39]:
housing_data.target[:3]

array([ 4.526,  3.585,  3.521])