In [1]:
import numpy as np

In [4]:
a = np.zeros((3,3,3))

In [5]:
a

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [6]:
np.ones((3,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [8]:
np.ones_like(a)

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [13]:
z = np.full(fill_value='hello', shape=(3,3))

In [16]:
z[0][0] = 'abcdefghi'

In [17]:
z

array([['abcde', 'hello', 'hello'],
       ['hello', 'hello', 'hello'],
       ['hello', 'hello', 'hello']], dtype='<U5')

In [18]:
np.arange(5,1,-1)

array([5, 4, 3, 2])

In [21]:
data = np.random.randint(2,10,(3,3,3))

In [23]:
data.ndim

3

In [24]:
data.shape

(3, 3, 3)

In [25]:
data.size

27

In [26]:
a = np.array([1,2,3,4,5])

In [27]:
a

array([1, 2, 3, 4, 5])

In [28]:
a.shape

(5,)

In [29]:
a.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [31]:
a.reshape(5,1,1)

array([[[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]]])

In [32]:
a = np.random.randint(2,10,(4,4))

In [33]:
a

array([[9, 2, 3, 5],
       [3, 2, 8, 3],
       [7, 4, 7, 2],
       [5, 6, 4, 4]])

In [36]:
a.reshape(2,-1,)

array([[9, 2, 3, 5, 3, 2, 8, 3],
       [7, 4, 7, 2, 5, 6, 4, 4]])

In [37]:
a = np.random.randint(2,10,(5,5))

In [38]:
a

array([[2, 6, 4, 2, 5],
       [8, 2, 6, 9, 4],
       [8, 3, 7, 6, 4],
       [4, 4, 8, 9, 7],
       [9, 5, 5, 2, 2]])

In [39]:
a[:,2:4]

array([[4, 2],
       [6, 9],
       [7, 6],
       [8, 9],
       [5, 2]])

In [40]:
a[2:4,:]

array([[8, 3, 7, 6, 4],
       [4, 4, 8, 9, 7]])

In [41]:
a[1:4,1:4]

array([[2, 6, 9],
       [3, 7, 6],
       [4, 8, 9]])

In [42]:
a

array([[2, 6, 4, 2, 5],
       [8, 2, 6, 9, 4],
       [8, 3, 7, 6, 4],
       [4, 4, 8, 9, 7],
       [9, 5, 5, 2, 2]])

In [45]:
d = np.random.randint(2,5,(12,12,12))

In [46]:
d[:,2:5,4:6]

array([[[4, 2],
        [2, 3],
        [4, 2]],

       [[4, 3],
        [3, 3],
        [3, 3]],

       [[2, 4],
        [3, 2],
        [3, 4]],

       [[3, 4],
        [2, 3],
        [4, 2]],

       [[4, 2],
        [4, 3],
        [4, 4]],

       [[2, 3],
        [3, 4],
        [3, 3]],

       [[2, 2],
        [4, 2],
        [2, 2]],

       [[4, 2],
        [2, 2],
        [4, 4]],

       [[3, 3],
        [2, 4],
        [2, 3]],

       [[3, 2],
        [3, 4],
        [3, 4]],

       [[4, 3],
        [3, 2],
        [2, 3]],

       [[3, 4],
        [4, 2],
        [4, 2]]])

In [48]:
a.ravel()

array([2, 6, 4, 2, 5, 8, 2, 6, 9, 4, 8, 3, 7, 6, 4, 4, 4, 8, 9, 7, 9, 5,
       5, 2, 2])

In [52]:
a

array([[2, 6, 4, 2, 5],
       [8, 2, 6, 9, 4],
       [8, 3, 7, 6, 4],
       [4, 4, 8, 9, 7],
       [9, 5, 5, 2, 2]])

In [50]:
np.hstack([a,a])

array([[2, 6, 4, 2, 5, 2, 6, 4, 2, 5],
       [8, 2, 6, 9, 4, 8, 2, 6, 9, 4],
       [8, 3, 7, 6, 4, 8, 3, 7, 6, 4],
       [4, 4, 8, 9, 7, 4, 4, 8, 9, 7],
       [9, 5, 5, 2, 2, 9, 5, 5, 2, 2]])

In [51]:
np.vstack([a,a])

array([[2, 6, 4, 2, 5],
       [8, 2, 6, 9, 4],
       [8, 3, 7, 6, 4],
       [4, 4, 8, 9, 7],
       [9, 5, 5, 2, 2],
       [2, 6, 4, 2, 5],
       [8, 2, 6, 9, 4],
       [8, 3, 7, 6, 4],
       [4, 4, 8, 9, 7],
       [9, 5, 5, 2, 2]])

In [54]:
u,v = np.hsplit(a,[3])

In [55]:
u

array([[2, 6, 4],
       [8, 2, 6],
       [8, 3, 7],
       [4, 4, 8],
       [9, 5, 5]])

In [56]:
v

array([[2, 5],
       [9, 4],
       [6, 4],
       [9, 7],
       [2, 2]])

In [58]:
u,v,w = np.vsplit(a,[2,4])

In [59]:
u

array([[2, 6, 4, 2, 5],
       [8, 2, 6, 9, 4]])

In [60]:
v

array([[8, 3, 7, 6, 4],
       [4, 4, 8, 9, 7]])

In [61]:
w

array([[9, 5, 5, 2, 2]])

In [62]:
np.sum([a,a])

262

In [63]:
a

array([[2, 6, 4, 2, 5],
       [8, 2, 6, 9, 4],
       [8, 3, 7, 6, 4],
       [4, 4, 8, 9, 7],
       [9, 5, 5, 2, 2]])

In [64]:
np.mean(a)

5.24

In [65]:
np.median(a)

5.0

In [66]:
a = np.array([3,4,5,6,7])

In [67]:
np.cumsum(a)

array([ 3,  7, 12, 18, 25], dtype=int32)

In [68]:
np.argmax(a)

4

In [69]:
a

array([3, 4, 5, 6, 7])

In [102]:
d = np.random.randint(2,51,(4,4))

In [79]:
d

array([[19, 34, 49, 12],
       [29, 34, 41, 48],
       [37, 48, 32, 26],
       [30, 34, 25, 19]])

In [81]:
np.argmax(d,axis=0)

array([2, 2, 0, 1], dtype=int64)

In [84]:
np.matmul(d,d)

array([[3520, 4562, 4193, 3362],
       [4494, 5742, 5327, 3958],
       [4059, 5310, 5455, 4074],
       [3051, 4022, 4139, 3003]])

In [85]:
np.cov(a)

array(2.5)

In [86]:
np.std(a)

1.4142135623730951

In [93]:
d = np.array([1,2,3,4]).reshape(2,1,2,1)
d

array([[[[1],
         [2]]],


       [[[3],
         [4]]]])

In [95]:
np.squeeze(d).shape

(2, 2)

In [97]:
np.sqrt(d)

array([[[[1.        ],
         [1.41421356]]],


       [[[1.73205081],
         [2.        ]]]])

In [100]:
np.choose(a=np.random.randint(0,2,10), choices=['hello','hi']).reshape(2,5)

array([['hello', 'hello', 'hi', 'hello', 'hi'],
       ['hello', 'hi', 'hello', 'hi', 'hello']], dtype='<U5')

In [101]:
d

array([[[[1],
         [2]]],


       [[[3],
         [4]]]])

In [103]:
np.max(d,axis=1)

array([41, 48, 37, 50])

In [104]:
d

array([[30, 40, 41, 12],
       [48, 40, 48, 18],
       [16, 37,  2, 17],
       [37, 38, 13, 50]])

In [106]:
np.max(d,axis=0)

array([48, 40, 48, 50])

In [107]:
d = np.random.randint(2,51,(4,4,4))

In [118]:
np.max(d,axis=1)

array([[48, 41, 50, 43],
       [33, 41, 34, 44],
       [43, 43, 46, 32],
       [42, 27, 45, 45]])

In [113]:
d

array([[[39, 41, 20, 16],
        [30,  3, 50, 43],
        [48, 17, 44, 18],
        [17, 17,  9, 28]],

       [[33, 13, 24, 38],
        [11, 41, 16, 44],
        [25, 25, 22, 28],
        [17, 32, 34, 17]],

       [[27, 39, 33, 16],
        [43, 41, 31, 17],
        [34, 18, 46, 32],
        [36, 43,  8, 18]],

       [[32, 17, 36, 45],
        [38, 27,  5, 17],
        [42,  4, 45, 33],
        [12, 16,  2, 11]]])

In [119]:
a = np.array([1,2,3,4])

In [120]:
a

array([1, 2, 3, 4])

In [121]:
a + a

array([2, 4, 6, 8])

In [123]:
a + 5

array([6, 7, 8, 9])

In [124]:
a

array([1, 2, 3, 4])

In [125]:
a + 5 

array([6, 7, 8, 9])

In [126]:
b = np.array([[1,1,1,1],[2,2,2,2]])

In [127]:
b.shape

(2, 4)

In [129]:
a.shape

(4,)

In [130]:
b + a

array([[2, 3, 4, 5],
       [3, 4, 5, 6]])

In [131]:
a

array([1, 2, 3, 4])

In [132]:
b

array([[1, 1, 1, 1],
       [2, 2, 2, 2]])

In [133]:
c = np.array([[1,1,1,1],[2,2,2,2],[3,3,3,3]])

In [134]:
c.shape

(3, 4)

In [135]:
b.shape

(2, 4)

In [2]:
import numpy as np
a = np.array([[1,2],[2,3],[3,4]])
b = np.array([[2,2],[3,3]])

In [143]:
a.shape

(3, 2)

In [144]:
b.shape

(1, 2)

In [145]:
a - b

array([[-1,  0],
       [ 0,  1],
       [ 1,  2]])

In [3]:
a.reshape(1,3,2) - b.reshape(2,1,2)

array([[[-1,  0],
        [ 0,  1],
        [ 1,  2]],

       [[-2, -1],
        [-1,  0],
        [ 0,  1]]])