In [16]:
from sklearn.preprocessing import StandardScaler,OneHotEncoder

In [2]:
std = StandardScaler()

In [3]:
import pandas as pd

In [5]:
df = pd.DataFrame({'A':[1,2,3,4,5],'B':[4,5,6,7,9]})

In [15]:
std.fit_transform(df)[:,0].std()

0.9999999999999999

In [10]:
df.std()

A    1.581139
B    1.923538
dtype: float64

In [12]:
df.describe()

A         B
count  5.000000  5.000000
mean   3.000000  6.200000
std    1.581139  1.923538
min    1.000000  4.000000
25%    2.000000  5.000000
50%    3.000000  6.000000
75%    4.000000  7.000000
max    5.000000  9.000000

In [17]:
enc = OneHotEncoder()

In [25]:
enc.fit([[1],[2],[3],[1]])

OneHotEncoder(categorical_features='all', dtype=<class 'numpy.float64'>,
       handle_unknown='error', n_values='auto', sparse=True)

In [28]:
enc.transform([[2],[1]]).toarray()

array([[0., 1., 0.],
       [1., 0., 0.]])

In [27]:
enc.active_features_

array([1, 2, 3], dtype=int64)

In [29]:
from sklearn.feature_extraction import DictVectorizer
dv = DictVectorizer()

In [36]:
measurements = [
    {'city': 'Dubai', 'temperature': 'low'},
    {'city': 'London', 'temperature': 'medium'},
    {'city': 'San Francisco', 'temperature': 'high'},
]

In [37]:
dv.fit(measurements)

DictVectorizer(dtype=<class 'numpy.float64'>, separator='=', sort=True,
        sparse=True)

In [38]:
dv.feature_names_

['city=Dubai',
 'city=London',
 'city=San Francisco',
 'temperature=high',
 'temperature=low',
 'temperature=medium']

In [39]:
new_measurements = [
    {'city': 'Dubai', 'temperature': 'low'},
    {'city': 'London', 'temperature': 'high'},
    {'city': 'Bangalore', 'temperature': 'none'},
]
dv.transform(new_measurements).toarray()

array([[1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [42]:
corpus  = [
     'This is the first document awesome food.',
     'This is the second second document.',
     'And the third one the is mission impossible.',
     'Is this the first document?',
]

In [44]:
df = pd.DataFrame({'text':corpus})

In [45]:
df

text
0      This is the first document awesome food.
1           This is the second second document.
2  And the third one the is mission impossible.
3                   Is this the first document?

In [57]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(stop_words='english',ngram_range=[1,2])

In [58]:
cv.fit(df.text)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=[1, 2], preprocessor=None, stop_words='english',
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [59]:
cv.transform(df.text).toarray()

array([[1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 2, 1, 1],
       [0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int64)

In [60]:
cv.get_feature_names()

['awesome',
 'awesome food',
 'document',
 'document awesome',
 'food',
 'impossible',
 'mission',
 'mission impossible',
 'second',
 'second document',
 'second second']

In [61]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [74]:
vectorizer = TfidfVectorizer(vocabulary=['second','document'])

In [75]:
vectorizer.fit(df.text)

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), norm='l2', preprocessor=None, smooth_idf=True,
        stop_words=None, strip_accents=None, sublinear_tf=False,
        token_pattern='(?u)\\b\\w\\w+\\b', tokenizer=None, use_idf=True,
        vocabulary=['second', 'document'])

In [76]:
import numpy as np
np.round(vectorizer.transform(df.text).toarray(),2)

array([[0.  , 1.  ],
       [0.95, 0.3 ],
       [0.  , 0.  ],
       [0.  , 1.  ]])

In [77]:
vectorizer.get_feature_names()

['second', 'document']

In [78]:
from sklearn.feature_extraction.text import HashingVectorizer

In [79]:
hv =  HashingVectorizer (n_features=5)

In [71]:
hv.fit(df.text)

HashingVectorizer(alternate_sign=True, analyzer='word', binary=False,
         decode_error='strict', dtype=<class 'numpy.float64'>,
         encoding='utf-8', input='content', lowercase=True, n_features=5,
         ngram_range=(1, 1), non_negative=False, norm='l2',
         preprocessor=None, stop_words=None, strip_accents=None,
         token_pattern='(?u)\\b\\w\\w+\\b', tokenizer=None)

In [73]:
hv

5