In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])

In [3]:
b = np.array([ [1,2,3,4], [5,6,7,8]])

In [4]:
a

array([1, 2, 3, 4])

In [5]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
a + b

array([[ 2,  4,  6,  8],
       [ 6,  8, 10, 12]])

In [7]:
c = np.array([ [1,2,3,4], [5,6,7,8]])

In [8]:
b + c 

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [9]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
c

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
b * c

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [12]:
a

array([1, 2, 3, 4])

In [15]:
b.shape

(2, 4)

In [14]:
b.ndim

2

In [16]:
a.shape

(4,)

### Rule 1
The first rule of broadcasting is that if all input arrays do not have the same number of dimensions, a “1” will be repeatedly prepended to the shapes of the smaller arrays until all the arrays have the same number of dimensions.

In [17]:
a.reshape(1,4)

array([[1, 2, 3, 4]])

### Rule 2
The second rule of broadcasting ensures that arrays with a size of 1 along a particular dimension act as if they had the size of the array with the largest shape along that dimension. The value of the array element is assumed to be the same along that dimension for the “broadcast” array.

In [18]:
a = np.array([ [1,2,3], [5,6,7]])

In [19]:
b = np.array([ [1,2,3,4], [5,6,7,4], [8,9,0,1]])

In [20]:
a.shape

(2, 3)

In [21]:
b.shape

(3, 4)

In [22]:
b.T.shape

(4, 3)

In [24]:
a.shape

(2, 3)

In [25]:
b.shape

(3, 4)

In [27]:
a.reshape(2,3,1) + b.reshape(1,3,4)

array([[[ 2,  3,  4,  5],
        [ 7,  8,  9,  6],
        [11, 12,  3,  4]],

       [[ 6,  7,  8,  9],
        [11, 12, 13, 10],
        [15, 16,  7,  8]]])

In [28]:
a.reshape(2,3,1)

array([[[1],
        [2],
        [3]],

       [[5],
        [6],
        [7]]])

In [29]:
b.reshape(1,3,4)

array([[[1, 2, 3, 4],
        [5, 6, 7, 4],
        [8, 9, 0, 1]]])

In [30]:
a = np.random.randint(5,10,size=(2,3,4))
b = np.random.randint(5,10,size=(6,5))

In [31]:
a.reshape(1,1,2,3,4) + b.reshape(6,5,1,1,1)


array([[[[[11, 13, 13, 11],
          [15, 13, 13, 11],
          [14, 12, 11, 13]],

         [[11, 13, 15, 13],
          [15, 12, 11, 11],
          [14, 13, 14, 11]]],


        [[[13, 15, 15, 13],
          [17, 15, 15, 13],
          [16, 14, 13, 15]],

         [[13, 15, 17, 15],
          [17, 14, 13, 13],
          [16, 15, 16, 13]]],


        [[[11, 13, 13, 11],
          [15, 13, 13, 11],
          [14, 12, 11, 13]],

         [[11, 13, 15, 13],
          [15, 12, 11, 11],
          [14, 13, 14, 11]]],


        [[[13, 15, 15, 13],
          [17, 15, 15, 13],
          [16, 14, 13, 15]],

         [[13, 15, 17, 15],
          [17, 14, 13, 13],
          [16, 15, 16, 13]]],


        [[[13, 15, 15, 13],
          [17, 15, 15, 13],
          [16, 14, 13, 15]],

         [[13, 15, 17, 15],
          [17, 14, 13, 13],
          [16, 15, 16, 13]]]],



       [[[[13, 15, 15, 13],
          [17, 15, 15, 13],
          [16, 14, 13, 15]],

         [[13, 15, 17, 15],
          [17,

In [32]:
a = np.random.randint(10,size=(3,4))

In [33]:
b = np.random.randint(20, size=(4,5))

In [34]:
np.matmul(a,b)

array([[ 37, 151, 113,  67, 175],
       [201, 200, 295, 243, 308],
       [195, 217, 269, 241, 290]])

In [35]:
a * b

ValueError: operands could not be broadcast together with shapes (3,4) (4,5) 

In [36]:
a = np.arange(10)

In [37]:
b = a

In [38]:
a[0] = 88

In [39]:
b

array([88,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [40]:
a is b

True

In [41]:
c = a.view()

In [42]:
c

array([88,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [43]:
a[0] = 99

In [44]:
a

array([99,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [45]:
c

array([99,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [48]:
c = c.reshape(2,5)

In [49]:
a

array([99,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [51]:
a = a.reshape(5,2)

In [52]:
c

array([[99,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9]])

In [53]:
a

array([[99,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9]])

In [54]:
a

array([[99,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9]])

In [55]:
z = a.copy()

In [56]:
z

array([[99,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9]])

In [58]:
a[0][1] = 88

In [59]:
a

array([[99, 88],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9]])

In [60]:
z

array([[99,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9]])