In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])

In [3]:
np.sum(a)

15

In [11]:
b = np.arange(100).reshape(10,10)

In [5]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [6]:
np.sum(b)

4950

In [8]:
np.sum(b, axis=1)

array([ 45, 145, 245, 345, 445, 545, 645, 745, 845, 945])

In [9]:
np.sum(b, axis=0)

array([450, 460, 470, 480, 490, 500, 510, 520, 530, 540])

In [12]:
np.arange(100,1,-1)

array([100,  99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,
        87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  76,  75,
        74,  73,  72,  71,  70,  69,  68,  67,  66,  65,  64,  63,  62,
        61,  60,  59,  58,  57,  56,  55,  54,  53,  52,  51,  50,  49,
        48,  47,  46,  45,  44,  43,  42,  41,  40,  39,  38,  37,  36,
        35,  34,  33,  32,  31,  30,  29,  28,  27,  26,  25,  24,  23,
        22,  21,  20,  19,  18,  17,  16,  15,  14,  13,  12,  11,  10,
         9,   8,   7,   6,   5,   4,   3,   2])

In [13]:
np.mean(b)

49.5

In [14]:
np.argmax(b)

99

In [15]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [16]:
np.argmin(b)

0

In [17]:
b.argmax()

99

In [21]:
z = np.array([4,2,1,3,9])

In [20]:
np.argsort(z)

array([2, 1, 3, 0, 4], dtype=int64)

In [23]:
np.argsort(b)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]], dtype=int64)

In [24]:
np.cov(b)

array([[ 9.16666667,  9.16666667,  9.16666667,  9.16666667,  9.16666667,
         9.16666667,  9.16666667,  9.16666667,  9.16666667,  9.16666667],
       [ 9.16666667,  9.16666667,  9.16666667,  9.16666667,  9.16666667,
         9.16666667,  9.16666667,  9.16666667,  9.16666667,  9.16666667],
       [ 9.16666667,  9.16666667,  9.16666667,  9.16666667,  9.16666667,
         9.16666667,  9.16666667,  9.16666667,  9.16666667,  9.16666667],
       [ 9.16666667,  9.16666667,  9.16666667,  9.16666667,  9.16666667,
         9.16666667,  9.16666667,  9.16666667,  9.16666667,  9.16666667],
       [ 9.16666667,  9.16666667,  9.16666667,  9.16666667,  9.16666667,
         9.16666667,  9.16666667,  9.16666667,  9.16666667,  9.16666667],
       [ 9.16666667,  9.16666667,  9.16666667,  9.16666667,  9.16666667,
         9.16666667,  9.16666667,  9.16666667,  9.16666667,  9.16666667],
       [ 9.16666667,  9.16666667,  9.16666667,  9.16666667,  9.16666667,
         9.16666667,  9.16666667,  9.16666667

In [25]:
np.cov(z)

array(9.7)

In [26]:
np.where(z > 2)

(array([0, 3, 4], dtype=int64),)

In [27]:
z

array([4, 2, 1, 3, 9])

In [29]:
np.where(z == 1)

(array([2], dtype=int64),)

In [30]:
np.where( b > 50)

(array([5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7,
        7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9, 9,
        9, 9, 9], dtype=int64),
 array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3,
        4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6,
        7, 8, 9], dtype=int64))

In [31]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [32]:
np.cumsum(z)

array([ 4,  6,  7, 10, 19], dtype=int32)

In [33]:
z

array([4, 2, 1, 3, 9])

In [34]:
np.cumprod(z)

array([  4,   8,   8,  24, 216], dtype=int32)

In [44]:

choices = [4,5,6,7]

In [48]:
np.choose([2,3,2], choices=choices)

array([6, 7, 6])

In [49]:
choices = [[0, 1, 2, 3], [10, 11, 12, 13],[20, 21, 22, 23], [30, 31, 32, 33]]

In [51]:
np.choose([[1],[2]], choices=choices)

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [61]:
np.choose([[1]], choices=choices)[0][2]

12

In [62]:
b.T

array([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
       [ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91],
       [ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92],
       [ 3, 13, 23, 33, 43, 53, 63, 73, 83, 93],
       [ 4, 14, 24, 34, 44, 54, 64, 74, 84, 94],
       [ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95],
       [ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96],
       [ 7, 17, 27, 37, 47, 57, 67, 77, 87, 97],
       [ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98],
       [ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99]])

In [63]:
np.sqrt(z)

array([ 2.        ,  1.41421356,  1.        ,  1.73205081,  3.        ])

In [64]:
z

array([4, 2, 1, 3, 9])

In [65]:
for i in z:
    print (i)

4
2
1
3
9
