In [1]:
import numpy as np

In [2]:
np.zeros(4)

array([0., 0., 0., 0.])

In [4]:
np.ones((5,5,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [6]:
2 * np.eye(M=3,N=3)

array([[2., 0., 0.],
       [0., 2., 0.],
       [0., 0., 2.]])

In [11]:
a = np.random.randint(0,10,size=(4,4))

In [12]:
a.shape

(4, 4)

In [13]:
a.ndim

2

In [14]:
a.size

16

In [26]:
a = np.linspace(1,10,20)

In [28]:
a[2:5]

array([1.94736842, 2.42105263, 2.89473684])

In [34]:
a = np.arange(0,100).reshape(10,10)

In [36]:
a[:,1:4]

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33],
       [41, 42, 43],
       [51, 52, 53],
       [61, 62, 63],
       [71, 72, 73],
       [81, 82, 83],
       [91, 92, 93]])

In [37]:
a[3:6,:]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [38]:
a[0][0] = 9999

In [39]:
a

array([[9999,    1,    2,    3,    4,    5,    6,    7,    8,    9],
       [  10,   11,   12,   13,   14,   15,   16,   17,   18,   19],
       [  20,   21,   22,   23,   24,   25,   26,   27,   28,   29],
       [  30,   31,   32,   33,   34,   35,   36,   37,   38,   39],
       [  40,   41,   42,   43,   44,   45,   46,   47,   48,   49],
       [  50,   51,   52,   53,   54,   55,   56,   57,   58,   59],
       [  60,   61,   62,   63,   64,   65,   66,   67,   68,   69],
       [  70,   71,   72,   73,   74,   75,   76,   77,   78,   79],
       [  80,   81,   82,   83,   84,   85,   86,   87,   88,   89],
       [  90,   91,   92,   93,   94,   95,   96,   97,   98,   99]])

In [41]:
d = a.reshape(100)

In [44]:
d.reshape(-1,5)

array([[9999,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9],
       [  10,   11,   12,   13,   14],
       [  15,   16,   17,   18,   19],
       [  20,   21,   22,   23,   24],
       [  25,   26,   27,   28,   29],
       [  30,   31,   32,   33,   34],
       [  35,   36,   37,   38,   39],
       [  40,   41,   42,   43,   44],
       [  45,   46,   47,   48,   49],
       [  50,   51,   52,   53,   54],
       [  55,   56,   57,   58,   59],
       [  60,   61,   62,   63,   64],
       [  65,   66,   67,   68,   69],
       [  70,   71,   72,   73,   74],
       [  75,   76,   77,   78,   79],
       [  80,   81,   82,   83,   84],
       [  85,   86,   87,   88,   89],
       [  90,   91,   92,   93,   94],
       [  95,   96,   97,   98,   99]])

In [43]:
d.reshape(2,-1)

array([[9999,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
          11,   12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
          22,   23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
          33,   34,   35,   36,   37,   38,   39,   40,   41,   42,   43,
          44,   45,   46,   47,   48,   49],
       [  50,   51,   52,   53,   54,   55,   56,   57,   58,   59,   60,
          61,   62,   63,   64,   65,   66,   67,   68,   69,   70,   71,
          72,   73,   74,   75,   76,   77,   78,   79,   80,   81,   82,
          83,   84,   85,   86,   87,   88,   89,   90,   91,   92,   93,
          94,   95,   96,   97,   98,   99]])

In [47]:
d.reshape(-1,1)

array([[9999],
       [   1],
       [   2],
       [   3],
       [   4],
       [   5],
       [   6],
       [   7],
       [   8],
       [   9],
       [  10],
       [  11],
       [  12],
       [  13],
       [  14],
       [  15],
       [  16],
       [  17],
       [  18],
       [  19],
       [  20],
       [  21],
       [  22],
       [  23],
       [  24],
       [  25],
       [  26],
       [  27],
       [  28],
       [  29],
       [  30],
       [  31],
       [  32],
       [  33],
       [  34],
       [  35],
       [  36],
       [  37],
       [  38],
       [  39],
       [  40],
       [  41],
       [  42],
       [  43],
       [  44],
       [  45],
       [  46],
       [  47],
       [  48],
       [  49],
       [  50],
       [  51],
       [  52],
       [  53],
       [  54],
       [  55],
       [  56],
       [  57],
       [  58],
       [  59],
       [  60],
       [  61],
       [  62],
       [  63],
       [  64],
       [  65],
       [  

In [52]:
d[:,np.newaxis]

array([[9999],
       [   1],
       [   2],
       [   3],
       [   4],
       [   5],
       [   6],
       [   7],
       [   8],
       [   9],
       [  10],
       [  11],
       [  12],
       [  13],
       [  14],
       [  15],
       [  16],
       [  17],
       [  18],
       [  19],
       [  20],
       [  21],
       [  22],
       [  23],
       [  24],
       [  25],
       [  26],
       [  27],
       [  28],
       [  29],
       [  30],
       [  31],
       [  32],
       [  33],
       [  34],
       [  35],
       [  36],
       [  37],
       [  38],
       [  39],
       [  40],
       [  41],
       [  42],
       [  43],
       [  44],
       [  45],
       [  46],
       [  47],
       [  48],
       [  49],
       [  50],
       [  51],
       [  52],
       [  53],
       [  54],
       [  55],
       [  56],
       [  57],
       [  58],
       [  59],
       [  60],
       [  61],
       [  62],
       [  63],
       [  64],
       [  65],
       [  

In [64]:
a1,a2,a3 = np.hsplit(a,[3,6])

In [65]:
a1

array([[9999,    1,    2],
       [  10,   11,   12],
       [  20,   21,   22],
       [  30,   31,   32],
       [  40,   41,   42],
       [  50,   51,   52],
       [  60,   61,   62],
       [  70,   71,   72],
       [  80,   81,   82],
       [  90,   91,   92]])

In [66]:
a2

array([[ 3,  4,  5],
       [13, 14, 15],
       [23, 24, 25],
       [33, 34, 35],
       [43, 44, 45],
       [53, 54, 55],
       [63, 64, 65],
       [73, 74, 75],
       [83, 84, 85],
       [93, 94, 95]])

### 

In [67]:
a3

array([[ 6,  7,  8,  9],
       [16, 17, 18, 19],
       [26, 27, 28, 29],
       [36, 37, 38, 39],
       [46, 47, 48, 49],
       [56, 57, 58, 59],
       [66, 67, 68, 69],
       [76, 77, 78, 79],
       [86, 87, 88, 89],
       [96, 97, 98, 99]])

In [69]:
a1,a2,a3,a4 = np.vsplit(a,[3,5,7])

In [70]:
a1

array([[9999,    1,    2,    3,    4,    5,    6,    7,    8,    9],
       [  10,   11,   12,   13,   14,   15,   16,   17,   18,   19],
       [  20,   21,   22,   23,   24,   25,   26,   27,   28,   29]])

In [71]:
a2

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [72]:
a3

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [73]:
a4

array([[70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [74]:
a

array([[9999,    1,    2,    3,    4,    5,    6,    7,    8,    9],
       [  10,   11,   12,   13,   14,   15,   16,   17,   18,   19],
       [  20,   21,   22,   23,   24,   25,   26,   27,   28,   29],
       [  30,   31,   32,   33,   34,   35,   36,   37,   38,   39],
       [  40,   41,   42,   43,   44,   45,   46,   47,   48,   49],
       [  50,   51,   52,   53,   54,   55,   56,   57,   58,   59],
       [  60,   61,   62,   63,   64,   65,   66,   67,   68,   69],
       [  70,   71,   72,   73,   74,   75,   76,   77,   78,   79],
       [  80,   81,   82,   83,   84,   85,   86,   87,   88,   89],
       [  90,   91,   92,   93,   94,   95,   96,   97,   98,   99]])

In [77]:
np.sum(a,axis=1)

array([10044,   145,   245,   345,   445,   545,   645,   745,   845,
         945])

In [80]:
a = np.arange(10).reshape(2,5)

In [81]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [83]:
b = np.arange(20).reshape(4,5)

In [85]:
np.vstack([a,b])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [86]:
np.mean(a)

4.5

In [89]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [90]:
np.min(a,axis=0)

array([0, 1, 2, 3, 4])

In [ ]:
np.