In [1]:
import numpy as np

In [2]:
data = np.random.randint(1,10,size=(5,5))

In [3]:
data

array([[8, 3, 9, 2, 6],
       [4, 9, 7, 8, 8],
       [4, 3, 5, 3, 3],
       [4, 9, 5, 8, 6],
       [8, 3, 1, 3, 7]])

In [4]:
data + 5

array([[13,  8, 14,  7, 11],
       [ 9, 14, 12, 13, 13],
       [ 9,  8, 10,  8,  8],
       [ 9, 14, 10, 13, 11],
       [13,  8,  6,  8, 12]])

In [5]:
np.square(data)

array([[64,  9, 81,  4, 36],
       [16, 81, 49, 64, 64],
       [16,  9, 25,  9,  9],
       [16, 81, 25, 64, 36],
       [64,  9,  1,  9, 49]], dtype=int32)

In [8]:
new = np.array([[1],[2],[3],[4],[5]])

In [9]:
new.shape

(5, 1)

In [10]:
data + new

array([[ 9,  4, 10,  3,  7],
       [ 6, 11,  9, 10, 10],
       [ 7,  6,  8,  6,  6],
       [ 8, 13,  9, 12, 10],
       [13,  8,  6,  8, 12]])

In [11]:
data

array([[8, 3, 9, 2, 6],
       [4, 9, 7, 8, 8],
       [4, 3, 5, 3, 3],
       [4, 9, 5, 8, 6],
       [8, 3, 1, 3, 7]])

### Different sizes of data

In [12]:
s = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [13]:
s.shape

(3, 3)

In [14]:
t = np.array([[1,2,3],[4,5,6]])

In [15]:
t.shape

(2, 3)

In [16]:
s + t

ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 

In [17]:
s1 = s.reshape((3,1,3))
s2 = t.reshape((1,2,3))
s1 + s2

array([[[ 2,  4,  6],
        [ 5,  7,  9]],

       [[ 5,  7,  9],
        [ 8, 10, 12]],

       [[ 8, 10, 12],
        [11, 13, 15]]])

#### handling different dimension

In [21]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([5,6,7,4])

In [22]:
a.shape

(2, 3)

In [23]:
b.shape

(4,)

In [24]:
a + b

ValueError: operands could not be broadcast together with shapes (2,3) (4,) 

In [26]:
b1 = b.reshape((4,1,1))

In [27]:
a1 = a.reshape((1,2,3))

b1 + a1

array([[[ 6,  7,  8],
        [ 9, 10, 11]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[ 8,  9, 10],
        [11, 12, 13]],

       [[ 5,  6,  7],
        [ 8,  9, 10]]])