In [1]:
import numpy as np

#### Concatination
* 1-D Concatenation

In [2]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [3]:
np.concatenate([a,b,a])

array([1, 2, 3, 4, 5, 6, 1, 2, 3])

##### 2D Concatenation

In [8]:
np.random.seed(10)
data = np.random.randint(2,20,size=(5,5))

In [9]:
data

array([[11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7]])

In [10]:
np.concatenate([data,data], axis=0)

array([[11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7],
       [11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7]])

In [9]:
np.concatenate([data,data], axis=1)

array([[11,  6, 17,  2, 19, 11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2, 18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6, 12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10, 17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7,  6, 16, 19, 15,  7]])

In [11]:
### append
data

array([[11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7]])

In [16]:
a = [1,2,3,4,5]

In [17]:
np.append(data,a)

array([11,  6, 17,  2, 19, 18, 19, 10, 11,  2, 12, 10,  6, 18,  6, 17, 13,
       13,  3, 10,  6, 16, 19, 15,  7,  1,  2,  3,  4,  5])

In [18]:
np.append(data, [a], axis=0)

array([[11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7],
       [ 1,  2,  3,  4,  5]])

In [28]:

b = [1,2,3,4,4]

In [29]:
np.append(data,[b],axis=0)

array([[11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7],
       [ 1,  2,  3,  4,  4]])

In [19]:
np.hstack([data,data])

array([[11,  6, 17,  2, 19, 11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2, 18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6, 12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10, 17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7,  6, 16, 19, 15,  7]])

In [45]:
res = np.vstack([data,data])

In [46]:
res

array([[11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7],
       [11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7]])

In [37]:
b = np.array([1,2,3,4,5,6])
np.hstack([data, b.reshape(6,1)])

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [33]:
data.shape

(5, 5)

In [34]:
c = [b]

In [35]:
c.shape

AttributeError: 'list' object has no attribute 'shape'

In [19]:
data

array([[11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7]])

In [20]:
np.hsplit(data,[2])

[array([[11,  6],
        [18, 19],
        [12, 10],
        [17, 13],
        [ 6, 16]]), array([[17,  2, 19],
        [10, 11,  2],
        [ 6, 18,  6],
        [13,  3, 10],
        [19, 15,  7]])]

In [21]:
np.vsplit(data,[2,4])

[array([[11,  6, 17,  2, 19],
        [18, 19, 10, 11,  2]]), array([[12, 10,  6, 18,  6],
        [17, 13, 13,  3, 10]]), array([[ 6, 16, 19, 15,  7]])]

In [22]:
data

array([[11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7]])