In [1]:
import numpy as np

In [2]:
%timeit sum(range(10000))

450 µs ± 18.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [3]:
a = np.arange(100000)
b = np.arange(100000)

In [6]:
%timeit np.add(a,b)

402 µs ± 26.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [7]:
l1 = list(range(100000))
l2 = list(range(100000))

In [8]:
%timeit l1 + l2

10.9 ms ± 921 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [10]:
data = np.array([1,-2,3,4,-6,8,-4])

In [11]:
np.abs(data)

array([1, 2, 3, 4, 6, 8, 4])

In [12]:
data

array([ 1, -2,  3,  4, -6,  8, -4])

In [14]:
a = np.random.rand(10000)

In [15]:
%timeit max(a)

1.42 ms ± 27.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [16]:
%timeit np.max(a)

15.5 µs ± 790 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [17]:
np.mean(a)

0.49543712329232742

In [18]:
np.cos(a)

array([ 0.74381032,  0.85021361,  0.77148921, ...,  0.76306178,
        0.99099562,  0.92366042])

In [19]:
np.max(a)

0.99987164291606045

In [24]:
help(np.mean)

Help on function mean in module numpy.core.fromnumeric:

mean(a, axis=None, dtype=None, out=None, keepdims=<class 'numpy._globals._NoValue'>)
    Compute the arithmetic mean along the specified axis.
    
    Returns the average of the array elements.  The average is taken over
    the flattened array by default, otherwise over the specified axis.
    `float64` intermediate and return values are used for integer inputs.
    
    Parameters
    ----------
    a : array_like
        Array containing numbers whose mean is desired. If `a` is not an
        array, a conversion is attempted.
    axis : None or int or tuple of ints, optional
        Axis or axes along which the means are computed. The default is to
        compute the mean of the flattened array.
    
        .. versionadded:: 1.7.0
    
        If this is a tuple of ints, a mean is performed over multiple axes,
        instead of a single axis or all the axes as before.
    dtype : data-type, optional
        Type to use in 

In [26]:
a.sum()

4954.371232923274

In [27]:
np.sum(a)

4954.371232923274

In [28]:
a = np.array([1,-2,3,4])

In [29]:
np.argmax(a)

3

In [31]:
np.argmax(np.array([7,8,9,1]))

2

In [36]:
a = [1,2,1,2,3,5,7,3]

In [33]:
b = [0,0,0,0]

In [34]:
np.any(b)

False

In [35]:
np.any(a)

True

In [37]:
np.all(a)

True