In [1]:
import numpy as np

In [17]:
a = np.array([[1,2,3,4],[5,6,7,8],[5,5,5,5]])
b = np.array([[4,5,6,7],[3,3,3,3]])

In [3]:
a

array([1, 2, 3, 4])

In [4]:
a + 5

array([6, 7, 8, 9])

In [5]:
a + [5,5,5,5]

array([6, 7, 8, 9])

In [7]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
b

array([4, 5, 6, 7])

In [9]:
a + b

array([[ 5,  7,  9, 11],
       [ 9, 11, 13, 15]])

In [10]:
a.shape

(2, 4)

In [11]:
b.shape

(4,)

In [15]:
a + b.reshape(1,4)

array([[ 5,  7,  9, 11],
       [ 9, 11, 13, 15]])

In [16]:
b

array([4, 5, 6, 7])

In [18]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 5, 5, 5]])

In [19]:
b

array([[4, 5, 6, 7],
       [3, 3, 3, 3]])

In [21]:
a.reshape(3,1,4) + b.reshape(1,2,4)

array([[[ 5,  7,  9, 11],
        [ 4,  5,  6,  7]],

       [[ 9, 11, 13, 15],
        [ 8,  9, 10, 11]],

       [[ 9, 10, 11, 12],
        [ 8,  8,  8,  8]]])