In [47]:
import numpy as np

In [4]:
d = np.empty((2,2,2))

In [5]:
d

array([[[0.00000000e+000, 5.49400998e-321],
        [2.47032823e-323, 1.14433534e-311]],

       [[0.00000000e+000, 2.47032823e-323],
        [1.14433631e-311, 0.00000000e+000]]])

In [6]:
d = np.zeros((2,2,2))

In [7]:
d

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [10]:
d = np.ones((2,2,2,2))

In [11]:
d

array([[[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]]])

In [12]:
np.zeros_like(d)

array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]])

In [13]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(10,2,-1)

array([10,  9,  8,  7,  6,  5,  4,  3])

In [17]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [19]:
np.logspace(2,4,8)

array([  100.        ,   193.06977289,   372.75937203,   719.685673  ,
        1389.49549437,  2682.69579528,  5179.47467923, 10000.        ])

In [25]:
np.random.rand(2,2,2)

array([[[0.9736702 , 0.94049548],
        [0.42583076, 0.57620137]],

       [[0.8583991 , 0.15657767],
        [0.62736839, 0.18216954]]])

In [26]:
np.random.randint(0,6,size=(3,3))

array([[5, 2, 5],
       [1, 5, 2],
       [2, 4, 2]])

In [27]:
np.array([2,3,4,5,5,6])

array([2, 3, 4, 5, 5, 6])

In [28]:
d = np.random.randint(0,10,size=(5,5))

In [29]:
d

array([[7, 9, 3, 2, 4],
       [8, 0, 0, 4, 4],
       [9, 3, 5, 8, 7],
       [6, 2, 9, 2, 9],
       [8, 8, 2, 8, 6]])

In [30]:
d[:,:]

array([[7, 9, 3, 2, 4],
       [8, 0, 0, 4, 4],
       [9, 3, 5, 8, 7],
       [6, 2, 9, 2, 9],
       [8, 8, 2, 8, 6]])

In [31]:
d[:,1]

array([9, 0, 3, 2, 8])

In [32]:
d[:,1:4]

array([[9, 3, 2],
       [0, 0, 4],
       [3, 5, 8],
       [2, 9, 2],
       [8, 2, 8]])

In [33]:
d[1:4,1:4]

array([[0, 0, 4],
       [3, 5, 8],
       [2, 9, 2]])

In [36]:
d[::2,::2]

array([[7, 3, 4],
       [9, 5, 7],
       [8, 2, 6]])

In [35]:
d

array([[7, 9, 3, 2, 4],
       [8, 0, 0, 4, 4],
       [9, 3, 5, 8, 7],
       [6, 2, 9, 2, 9],
       [8, 8, 2, 8, 6]])

In [50]:
np.random.seed(6)
#d = np.random.randint(0,10,(6,6))

6

In [51]:
d

array([[2, 8, 9, 2, 8, 0],
       [2, 6, 1, 5, 3, 8],
       [2, 3, 8, 5, 4, 2],
       [8, 6, 1, 7, 8, 9],
       [3, 1, 6, 8, 5, 5],
       [3, 8, 9, 6, 6, 9]])

In [52]:
d.ndim

2

In [53]:
d.shape

(6, 6)

In [54]:
d.size

36

In [56]:
d.reshape(2,18)

array([[2, 8, 9, 2, 8, 0, 2, 6, 1, 5, 3, 8, 2, 3, 8, 5, 4, 2],
       [8, 6, 1, 7, 8, 9, 3, 1, 6, 8, 5, 5, 3, 8, 9, 6, 6, 9]])

In [57]:
d.reshape(-1,4)

array([[2, 8, 9, 2],
       [8, 0, 2, 6],
       [1, 5, 3, 8],
       [2, 3, 8, 5],
       [4, 2, 8, 6],
       [1, 7, 8, 9],
       [3, 1, 6, 8],
       [5, 5, 3, 8],
       [9, 6, 6, 9]])

In [58]:
d.reshape(-1,2)

array([[2, 8],
       [9, 2],
       [8, 0],
       [2, 6],
       [1, 5],
       [3, 8],
       [2, 3],
       [8, 5],
       [4, 2],
       [8, 6],
       [1, 7],
       [8, 9],
       [3, 1],
       [6, 8],
       [5, 5],
       [3, 8],
       [9, 6],
       [6, 9]])

In [64]:
a = np.array([1,2,3,43,5,6,6,6,6,6])

In [65]:
a.shape

(10,)

In [67]:
a.reshape(-1,2).shape

(5, 2)

In [68]:
a.reshape(-1,1).shape

(10, 1)

In [69]:
a

array([ 1,  2,  3, 43,  5,  6,  6,  6,  6,  6])

In [70]:
np.sum(a)

84

In [71]:
np.std(a)

11.672189169131899

In [72]:
np.mean(a)

8.4

In [73]:
d

array([[2, 8, 9, 2, 8, 0],
       [2, 6, 1, 5, 3, 8],
       [2, 3, 8, 5, 4, 2],
       [8, 6, 1, 7, 8, 9],
       [3, 1, 6, 8, 5, 5],
       [3, 8, 9, 6, 6, 9]])

In [74]:
np.sum(d,axis=1)

array([29, 25, 24, 39, 28, 41])

In [76]:
np.sum(d, axis=0)

array([20, 32, 34, 33, 34, 33])

In [86]:
d3 = np.random.randint(0,2,size=(3,3,3))

In [87]:
np.sum(d3,axis=0)

array([[1, 2, 0],
       [1, 0, 1],
       [1, 1, 1]])

In [88]:
d3

array([[[0, 1, 0],
        [0, 0, 0],
        [1, 0, 1]],

       [[1, 1, 0],
        [1, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 1],
        [0, 1, 0]]])

In [90]:
np.max(d,axis=1)

array([9, 8, 8, 9, 8, 9])

In [91]:
d

array([[2, 8, 9, 2, 8, 0],
       [2, 6, 1, 5, 3, 8],
       [2, 3, 8, 5, 4, 2],
       [8, 6, 1, 7, 8, 9],
       [3, 1, 6, 8, 5, 5],
       [3, 8, 9, 6, 6, 9]])

In [93]:
dn = np.array(["abc","def","ghi"])

In [95]:
dn[0] = 'aaaaaaa'

In [96]:
dn

array(['aaa', 'def', 'ghi'], dtype='<U3')

In [100]:
b = a + 10

In [101]:
b - a

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [103]:
np.max(d)

9

In [104]:
d

array([[2, 8, 9, 2, 8, 0],
       [2, 6, 1, 5, 3, 8],
       [2, 3, 8, 5, 4, 2],
       [8, 6, 1, 7, 8, 9],
       [3, 1, 6, 8, 5, 5],
       [3, 8, 9, 6, 6, 9]])

In [106]:
a

array([ 1,  2,  3, 43,  5,  6,  6,  6,  6,  6])

In [112]:
np.choose(a=[0,3,0,5],choices=[1,2,3,4,5,6])

array([1, 4, 1, 6])

In [109]:
np.choose(a=np.random.randint(0,2,size=(100)), choices=['cat','dog'])

array(['dog', 'cat', 'dog', 'dog', 'cat', 'dog', 'cat', 'dog', 'dog',
       'dog', 'dog', 'dog', 'dog', 'cat', 'cat', 'dog', 'dog', 'cat',
       'dog', 'cat', 'cat', 'cat', 'cat', 'dog', 'dog', 'cat', 'cat',
       'cat', 'cat', 'dog', 'cat', 'cat', 'dog', 'cat', 'dog', 'cat',
       'dog', 'cat', 'cat', 'cat', 'cat', 'dog', 'cat', 'dog', 'dog',
       'cat', 'cat', 'cat', 'cat', 'dog', 'cat', 'dog', 'cat', 'dog',
       'cat', 'dog', 'dog', 'cat', 'cat', 'dog', 'cat', 'cat', 'cat',
       'dog', 'cat', 'cat', 'cat', 'cat', 'cat', 'dog', 'cat', 'cat',
       'cat', 'dog', 'cat', 'cat', 'cat', 'cat', 'dog', 'cat', 'cat',
       'dog', 'dog', 'dog', 'cat', 'dog', 'cat', 'cat', 'dog', 'cat',
       'cat', 'cat', 'dog', 'dog', 'cat', 'dog', 'dog', 'cat', 'cat',
       'dog'], dtype='<U3')

In [110]:
np.random.randint(0,2,size=(100))

array([1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0])

In [113]:
a = np.array([1,2,3,4,5])

In [114]:
a

array([1, 2, 3, 4, 5])

In [115]:
a + 10

array([11, 12, 13, 14, 15])

In [116]:
a = np.array([[1,2,3,4],[5,6,7,8],[8,8,8,8]])

In [117]:
a.shape

(3, 4)

In [122]:
b = np.array([[7,7,7,7],[17,71,7,7]])

In [123]:
b

array([[ 7,  7,  7,  7],
       [17, 71,  7,  7]])

In [120]:
a + b

ValueError: operands could not be broadcast together with shapes (3,4) (2,4) 

In [121]:
a.reshape(1,3,4) + b.reshape(2,1,4)

array([[[ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [15, 15, 15, 15]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [15, 15, 15, 15]]])

In [124]:
blue = np.array([
    [1,1],
    [2,2],
    [3,3],
    [4,4]
])

In [125]:
red = np.array([
    [2,2],
    [4,4]
])

In [127]:
blue.reshape(1,4,2) - red.reshape(2,1,2)

array([[[-1, -1],
        [ 0,  0],
        [ 1,  1],
        [ 2,  2]],

       [[-3, -3],
        [-2, -2],
        [-1, -1],
        [ 0,  0]]])