In [1]:
import numpy as np

In [2]:
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])

In [3]:
a + b

array([5, 6, 7])

* If arrays are of same size, element to element operation takes place
* Because of broadcasting, scaler value 5 is converted into vector & ops takes place

In [4]:
a + 5

array([5, 6, 7])

In [6]:
a = np.array([ [1,2,3], [4,5,6] ])

In [8]:
a + 5

array([[ 6,  7,  8],
       [ 9, 10, 11]])

<img src="https://github.com/awantik/PythonDataScienceHandbook/raw/f2c4a8af3f6e7e5f455469839e31b09ab6c22868/notebooks/figures/02.05-broadcasting.png">

In [9]:
a = np.arange(3).reshape(3,1)

In [10]:
a

array([[0],
       [1],
       [2]])

In [11]:
b = np.arange(3)

In [12]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

Broadcasting in NumPy follows a strict set of rules to determine the interaction between the two arrays:

* Rule 1: If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.
* Rule 2: If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.
* Rule 3: If in any dimension the sizes disagree and neither is equal to 1, an error is raised.

In [13]:
M = np.ones((2, 3))
a = np.arange(3)

In [17]:
M.shape

(2, 3)

In [22]:
a.shape

(3,)

In [19]:
M + a

array([[ 1.,  2.,  3.],
       [ 1.,  2.,  3.]])

In [20]:
a + M

array([[ 1.,  2.,  3.],
       [ 1.,  2.,  3.]])

In [23]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [25]:
a = a.reshape(1,2,3)
b = b.reshape(3,1,3)

In [26]:
a + b

array([[[ 2,  4,  6],
        [ 5,  7,  9]],

       [[ 5,  7,  9],
        [ 8, 10, 12]],

       [[ 8, 10, 12],
        [11, 13, 15]]])