### Introduction to NumPy

* Fast Mathematical Computational Library
* General purpose library using list available in Python is slow
* Homogenous data structure
* Specialized for doing mathematical computation
* Internally implemented using C - so fast
* High dimensional Computation
* Inbuilt utilities
* Mutabale

#### NumPy Creation
* From list
* zero init
* one init
* default value initialized
* range
* random

In [2]:
import numpy as np

#### From list

In [3]:
a = np.array([2,3,4,4,5,1])

In [4]:
a

array([2, 3, 4, 4, 5, 1])

In [5]:
a = np.array([2,3,4,4,5,1], dtype=np.float16)

In [6]:
a.dtype

dtype('float16')

In [7]:
a

array([ 2.,  3.,  4.,  4.,  5.,  1.], dtype=float16)

In [8]:
b = np.array(['hello','world','friends'])

* The size of each element is decided by maximum size of word. 7 in this case

In [9]:
b.dtype

dtype('<U7')

In [9]:
b[0] = 'abcdefghijkl'

In [10]:
b

array(['abcdefg', 'world', 'friends'],
      dtype='<U7')

#### Zero & One init

In [10]:
z = np.zeros((4,4,4))

In [11]:
z

array([[[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]]])

In [12]:
a

array([ 2.,  3.,  4.,  4.,  5.,  1.], dtype=float16)

##### zero_like
* create new data structure of same dimension/size as passed and assign zero to it

In [14]:
np.zeros_like(a)

array([ 0.,  0.,  0.,  0.,  0.,  0.], dtype=float16)

##### ones

In [15]:
a = np.ones((3,3,3))

##### ones_like

In [16]:
np.ones_like(a)

array([[[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]],

       [[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]],

       [[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]]])

#### full
* Init all the contents with this

In [17]:
np.full( (6,6), 99)

array([[99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99]])

In [18]:
np.full((3,3), 'hello')

array([['hello', 'hello', 'hello'],
       ['hello', 'hello', 'hello'],
       ['hello', 'hello', 'hello']],
      dtype='<U5')

In [19]:
np.full_like(a, 10)

array([[[ 10.,  10.,  10.],
        [ 10.,  10.,  10.],
        [ 10.,  10.,  10.]],

       [[ 10.,  10.,  10.],
        [ 10.,  10.,  10.],
        [ 10.,  10.,  10.]],

       [[ 10.,  10.,  10.],
        [ 10.,  10.,  10.],
        [ 10.,  10.,  10.]]])

#### range
* Init a numpy array from start point to end point
* params - starting-point, ending-point & step size

In [20]:
np.arange(10, 20, 2)

array([10, 12, 14, 16, 18])

In [21]:
np.arange(15,10,-1)

array([15, 14, 13, 12, 11])

#### random

* Generating 10 numbers between 0 & 1

In [15]:
d = np.random.rand(16)
d

array([ 0.78624269,  0.5355401 ,  0.57644003,  0.54508723,  0.48233789,
        0.86392502,  0.6238696 ,  0.50277807,  0.49256303,  0.1874114 ,
        0.03400654,  0.78402114,  0.47684824,  0.36299129,  0.77557005,
        0.66057882])

In [16]:
d.reshape((4,4))

array([[ 0.78624269,  0.5355401 ,  0.57644003,  0.54508723],
       [ 0.48233789,  0.86392502,  0.6238696 ,  0.50277807],
       [ 0.49256303,  0.1874114 ,  0.03400654,  0.78402114],
       [ 0.47684824,  0.36299129,  0.77557005,  0.66057882]])

In [11]:
np.random.randn(4,4)

array([[-0.15440255, -0.43556559,  1.42966188, -0.10002879],
       [ 0.46332397, -0.8713814 ,  0.5408016 ,  0.38828278],
       [ 1.44139903,  0.24499885,  0.00591755, -1.70543495],
       [-0.2226114 , -0.00847272, -1.119423  ,  0.95547281]])

In [12]:
help(np.random.randn)

Help on built-in function randn:

randn(...) method of mtrand.RandomState instance
    randn(d0, d1, ..., dn)
    
    Return a sample (or samples) from the "standard normal" distribution.
    
    If positive, int_like or int-convertible arguments are provided,
    `randn` generates an array of shape ``(d0, d1, ..., dn)``, filled
    with random floats sampled from a univariate "normal" (Gaussian)
    distribution of mean 0 and variance 1 (if any of the :math:`d_i` are
    floats, they are first converted to integers by truncation). A single
    float randomly sampled from the distribution is returned if no
    argument is provided.
    
    This is a convenience function.  If you want an interface that takes a
    tuple as the first argument, use `numpy.random.standard_normal` instead.
    
    Parameters
    ----------
    d0, d1, ..., dn : int, optional
        The dimensions of the returned array, should be all positive.
        If no argument is given a single Python float is ret

* int array between 5 & 10

In [13]:
np.random.randint(5,10,size=(3,3))

array([[8, 5, 8],
       [5, 6, 6],
       [6, 9, 6]])

##### shuffle
* randomizes the contents

In [17]:
np.random.shuffle(d)

In [43]:
d

array([ 0.17911883,  0.81017228,  0.72763046,  0.62888571,  0.52937559,
        0.13116098,  0.20154966,  0.9429892 ,  0.85219881,  0.73766751])

##### seed
* controls the output 
* using same seed, we will get same output

In [23]:
np.random.seed(67)
np.random.randint(5,10,size=(3,7))

array([[8, 7, 6, 6, 8, 8, 6],
       [8, 5, 8, 9, 6, 7, 7],
       [7, 8, 5, 7, 6, 8, 7]])

### Accessing elements

In [25]:
np.random.seed(10)
data = np.random.randint(2,20,size=(5,5))

In [26]:
data

array([[11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7]])

#### Two ways to access this

In [27]:
data[2][1]

10

In [16]:
data[2,1]

10

In [28]:
data[1:4,1:4]

array([[19, 10, 11],
       [10,  6, 18],
       [13, 13,  3]])

#### Accessing only the first row

In [17]:
data[1]

array([18, 19, 10, 11,  2])

#### Accessing first onwards all the rows

In [18]:
data[1:]

array([[18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7]])

#### Accessing till row 2

In [19]:
data[:2]

array([[11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2]])

#### Column access

In [20]:
data[:,1:3]

array([[ 6, 17],
       [19, 10],
       [10,  6],
       [13, 13],
       [16, 19]])

* Question : Get slice containing 6,18,13,3

In [21]:
data[1:4, 1:4]

array([[19, 10, 11],
       [10,  6, 18],
       [13, 13,  3]])

In [22]:
data[2:3,2:3]

array([[6]])

#### Shape, Size & Dimension
* These are not functions but attributes

Provide information on dimension

In [29]:
data.shape

(5, 5)

Total size of data

In [30]:
data.size

25

ndim - returns num of dimension, 2 in matrix, 3 in 

In [23]:
data.ndim

2

#### Reshaping data
* Changes shape & dimension of data but not size

In [31]:
a = np.array([1,2,3,4,5,6])

In [32]:
a.shape

(6,)

In [73]:
a.ndim

1

In [20]:
b = a.reshape((2,3))
b

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
b.reshape(6)

array([1, 2, 3, 4, 5, 6])

In [27]:
b.ndim

2

In [78]:
b.shape

(2, 3)

In [32]:
b.shape

(3,)

In [80]:
a.reshape((3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [82]:
b.reshape((3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

#### Adding one dim

In [34]:
a = np.array([1,2,3,4,5,6])

#### Adds one dimension 

In [35]:
a.reshape((6,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [28]:
a.reshape(-1,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [29]:
a.reshape(-1,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [30]:
a.reshape(2,-1)

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
a.reshape(-1,1,1,1,1,1,1)

array([[[[[[[1]]]]]],





       [[[[[[2]]]]]],





       [[[[[[3]]]]]],





       [[[[[[4]]]]]],





       [[[[[[5]]]]]],





       [[[[[[6]]]]]]])

#### Yet another way to add one more dimension 

In [40]:
a[:,np.newaxis,np.newaxis]

array([[[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]],

       [[6]]])

In [34]:
data[:,np.newaxis]

array([[[11,  6, 17,  2, 19]],

       [[18, 19, 10, 11,  2]],

       [[12, 10,  6, 18,  6]],

       [[17, 13, 13,  3, 10]],

       [[ 6, 16, 19, 15,  7]]])

#### Convert data into 1-d of 25 elements

In [100]:
data.reshape(25)

array([11,  6, 17,  2, 19, 18, 19, 10, 11,  2, 12, 10,  6, 18,  6, 17, 13,
       13,  3, 10,  6, 16, 19, 15,  7])

In [99]:
data.reshape(*data.shape,1).shape

(5, 5, 1)

#### removal of dimension , converts into 1D data .i.e flattens it out

In [102]:
np.ravel(data)

array([11,  6, 17,  2, 19, 18, 19, 10, 11,  2, 12, 10,  6, 18,  6, 17, 13,
       13,  3, 10,  6, 16, 19, 15,  7])

### Concatination
* Combining data

#### Combining 1-D data

In [36]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [37]:
np.concatenate([x,y,x])

array([1, 2, 3, 4, 5, 6, 1, 2, 3])

#### Axis
* 0 - vertical
* 1 - horizontal

#### Combining 2D data
* by default axis zero

In [106]:
data

array([[11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7]])

In [107]:

np.concatenate([data,data])

array([[11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7],
       [11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7]])

In [108]:
np.concatenate([data,data], axis=1)

array([[11,  6, 17,  2, 19, 11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2, 18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6, 12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10, 17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7,  6, 16, 19, 15,  7]])

In [42]:
d1 = np.array([ [1,2,3], [4,5,6]])
d2 = np.array([ ['a','b','c'], ['d','e','f']])
np.concatenate([d1,d2])

array([['1', '2', '3'],
       ['4', '5', '6'],
       ['a', 'b', 'c'],
       ['d', 'e', 'f']],
      dtype='<U11')

#### append
* adds value at the end of the array

In [38]:
data

array([[11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7]])

In [39]:
np.append(data, [1,2,3,4,5])

array([11,  6, 17,  2, 19, 18, 19, 10, 11,  2, 12, 10,  6, 18,  6, 17, 13,
       13,  3, 10,  6, 16, 19, 15,  7,  1,  2,  3,  4,  5])

In [114]:
np.append(data, [[1,2,3,4,5]], axis=0)

array([[11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7],
       [ 1,  2,  3,  4,  5]])

In [119]:
data

array([[11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7]])

### horizontal stacking

In [120]:
np.hstack([data,data])

array([[11,  6, 17,  2, 19, 11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2, 18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6, 12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10, 17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7,  6, 16, 19, 15,  7]])

### vertical stacking

In [121]:
np.vstack([data,data])

array([[11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7],
       [11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7]])

#### Rules
* hstacking - num of rowst should be same 
* vstacking - num of cols should be same

### Splitting 

#### hsplit - splitting the horizontal axis

In [41]:
a,b,c = np.hsplit(data,[2,3])

In [42]:
a

array([[11,  6],
       [18, 19],
       [12, 10],
       [17, 13],
       [ 6, 16]])

In [43]:
b

array([[17],
       [10],
       [ 6],
       [13],
       [19]])

In [44]:
c

array([[ 2, 19],
       [11,  2],
       [18,  6],
       [ 3, 10],
       [15,  7]])

In [42]:
data

array([[11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7]])

#### vsplit - splitting the vertical axis

In [44]:
a,b = np.vsplit(data, [2])

In [45]:
a

array([[11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2]])

In [46]:
b

array([[12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7]])