In [1]:
import numpy as np

In [2]:
a = np.array([2,1,3,4])

In [3]:
a + 5

array([7, 6, 8, 9])

In [4]:
a.shape

(4,)

In [5]:
b = np.array([[1,2,3,4],[7,8,9,2]])

In [6]:
b

array([[1, 2, 3, 4],
       [7, 8, 9, 2]])

In [7]:
a

array([2, 1, 3, 4])

In [8]:
b.shape

(2, 4)

In [10]:
a

array([2, 1, 3, 4])

In [11]:
b + a

array([[ 3,  3,  6,  8],
       [ 9,  9, 12,  6]])

In [12]:
c = np.array([[1,2,3,4],[2,3,4,5],[3,4,5,6]])

In [13]:
c

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [14]:
b

array([[1, 2, 3, 4],
       [7, 8, 9, 2]])

In [15]:
c.shape

(3, 4)

In [16]:
b.shape

(2, 4)

In [17]:
c = np.array([[1,2,3,4],[2,3,4,5],[3,4,5,6],[5,6,7,8]])

In [18]:
c

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6],
       [5, 6, 7, 8]])

In [19]:
b

array([[1, 2, 3, 4],
       [7, 8, 9, 2]])

In [21]:
data1 = np.array([[1,2],[3,4],[5,4],[3,2],[2,2]])

In [22]:
data2 = np.array([[3,3],[5,5]])

In [23]:
data1.shape

(5, 2)

In [24]:
data2.shape

(2, 2)

In [27]:
res = data1.reshape(1,5,2) - data2.reshape(2,1,2)

In [28]:
res.shape

(2, 5, 2)