In [1]:
import numpy as np

In [4]:
x = np.random.randint(100, size=10)

In [5]:
x

array([32, 75, 57, 71, 22, 47, 11, 76, 17, 36])

In [6]:
ind = [3,7,4]

In [7]:
x[ind]

array([71, 76, 22])

#### Create 2D array using these indexes

In [9]:
ind = np.array([ [3,7], [4,5] ])

In [10]:
x[ind]

array([[71, 76],
       [22, 47]])

In [11]:
x

array([32, 75, 57, 71, 22, 47, 11, 76, 17, 36])

In [15]:
ind = [5,16,27]
x[5:8] = 0

In [16]:
x

array([32, 75, 57, 71, 22,  0,  0,  0, 17, 36])

In [17]:
x = np.arange(10)

In [18]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
x[[1,3,7]] *= 2

In [23]:
x

array([ 0,  2,  2,  6,  4,  5,  6, 14,  8,  9])

In [24]:
import pandas as pd

In [25]:
pd.__version__

'0.20.3'