In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5,6])

In [4]:
a

array([1, 2, 3, 4, 5, 6])

In [6]:
a[0:5]

array([1, 2, 3, 4, 5])

In [13]:
z = np.zeros((3,3,3))

In [14]:
z[1,1,1]

0.0

In [15]:
np.ones((2,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [20]:
d = np.empty((2,2,2))

In [22]:
f = np.zeros_like(d)

In [23]:
f

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [24]:
np.full((3,3,3),'abc')

array([[['abc', 'abc', 'abc'],
        ['abc', 'abc', 'abc'],
        ['abc', 'abc', 'abc']],

       [['abc', 'abc', 'abc'],
        ['abc', 'abc', 'abc'],
        ['abc', 'abc', 'abc']],

       [['abc', 'abc', 'abc'],
        ['abc', 'abc', 'abc'],
        ['abc', 'abc', 'abc']]], dtype='<U3')

In [37]:
z = np.random.randint(1,100,(4,8))

In [29]:
np.random.rand(10)

array([0.44275824, 0.74255663, 0.60452955, 0.34735695, 0.76464122,
       0.5963825 , 0.30773857, 0.46965907, 0.86531226, 0.83463864])

In [32]:
d = np.linspace(1,10,19)

In [33]:
d

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [34]:
d.shape

(19,)

In [38]:
z.shape

(4, 8)

In [40]:
z = z.reshape((2,16))

In [41]:
z

array([[63, 18, 54, 12, 98, 75,  3, 41, 19, 47, 45, 86, 57, 62, 40, 84],
       [53, 89, 15, 99, 34, 76, 50, 94, 73, 38, 63, 65, 60, 84, 37, 70]])

In [42]:
z.shape

(2, 16)

In [44]:
a = np.array([1,2,3,4,5,6])

In [45]:
a

array([1, 2, 3, 4, 5, 6])

In [47]:
a.shape

(6,)

In [49]:
a.reshape(-1,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [51]:
s = a.reshape(2,-1)

In [55]:
s = s.ravel()

In [56]:
s

array([1, 2, 3, 4, 5, 6])

In [58]:
np.mean(a)

3.5

In [59]:
a

array([1, 2, 3, 4, 5, 6])

In [60]:
np.std(a)

1.707825127659933

In [61]:
np.median(a)

3.5

In [64]:
a

array([1, 2, 3, 4, 5, 6])

In [66]:
a = np.random.randint(0,2,(4,4))

In [67]:
b = np.random.randint(0,2,(4,4))

In [68]:
a

array([[1, 0, 1, 1],
       [0, 1, 0, 1],
       [0, 0, 1, 0],
       [0, 0, 1, 0]])

In [69]:
b

array([[1, 0, 1, 1],
       [1, 0, 1, 0],
       [1, 1, 0, 0],
       [0, 1, 0, 1]])

In [70]:
np.vstack([a,b])

array([[1, 0, 1, 1],
       [0, 1, 0, 1],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [1, 0, 1, 1],
       [1, 0, 1, 0],
       [1, 1, 0, 0],
       [0, 1, 0, 1]])

In [72]:
d = np.hstack([a,b])

In [73]:
d

array([[1, 0, 1, 1, 1, 0, 1, 1],
       [0, 1, 0, 1, 1, 0, 1, 0],
       [0, 0, 1, 0, 1, 1, 0, 0],
       [0, 0, 1, 0, 0, 1, 0, 1]])

In [76]:
d1,d2 = np.vsplit(d,[2])

In [77]:
d1

array([[1, 0, 1, 1, 1, 0, 1, 1],
       [0, 1, 0, 1, 1, 0, 1, 0]])

In [78]:
d2

array([[0, 0, 1, 0, 1, 1, 0, 0],
       [0, 0, 1, 0, 0, 1, 0, 1]])

In [80]:
d1,d2,d3 = np.hsplit(d,[3,5])

In [81]:
d1

array([[1, 0, 1],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1]])

In [82]:
d2

array([[1, 1],
       [1, 1],
       [0, 1],
       [0, 0]])

In [83]:
d3

array([[0, 1, 1],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 1]])

In [87]:
data = np.random.randint(2,10,10)

In [88]:
data

array([4, 3, 6, 3, 7, 3, 4, 7, 5, 4])

In [89]:
np.max(data)

7

In [90]:
np.argmax(data)

4

In [91]:
np.argsort(data)

array([1, 3, 5, 0, 6, 9, 8, 2, 4, 7], dtype=int64)

In [92]:
data = np.random.randint(2,10,(5,5))

In [99]:
np.argsort(data,axis=0)

array([[1, 3, 2, 1, 0],
       [4, 2, 3, 2, 4],
       [0, 0, 4, 4, 3],
       [3, 4, 0, 0, 2],
       [2, 1, 1, 3, 1]], dtype=int64)

In [100]:
np.max(data,axis=1)

array([7, 9, 8, 9, 7])

In [101]:
data

array([[4, 7, 7, 7, 3],
       [3, 9, 8, 3, 8],
       [8, 5, 4, 4, 7],
       [5, 3, 5, 9, 6],
       [3, 7, 5, 4, 3]])

In [103]:
np.max(data[:,2])

8

In [112]:
data = np.random.randint(1,100,(2,2,2))

In [113]:
np.max(data,axis=1)

array([[35, 72],
       [99, 60]])

In [114]:
data

array([[[12, 72],
        [35, 62]],

       [[99, 60],
        [74, 13]]])

In [115]:
a

array([[1, 0, 1, 1],
       [0, 1, 0, 1],
       [0, 0, 1, 0],
       [0, 0, 1, 0]])

In [116]:
b

array([[1, 0, 1, 1],
       [1, 0, 1, 0],
       [1, 1, 0, 0],
       [0, 1, 0, 1]])

In [117]:
np.matmul(a,b)

array([[2, 2, 1, 2],
       [1, 1, 1, 1],
       [1, 1, 0, 0],
       [1, 1, 0, 0]])