In [1]:
import numpy as np

In [2]:
a = np.arange(10000)
b = np.arange(10000)

In [4]:
%timeit a + b

18.6 µs ± 781 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [5]:
%timeit np.cumsum(a)

61.7 µs ± 2.21 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [3]:
l = range(10000)

In [4]:
%timeit sum(l)

553 µs ± 46.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [6]:
%timeit np.cumsum(a)

60.3 µs ± 3.04 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [7]:
data = np.random.randint(1,10,size=(10,10))

In [9]:
np.sum(data,axis=0)

array([54, 59, 60, 55, 35, 59, 55, 44, 57, 49])

In [8]:
data

array([[4, 2, 5, 5, 5, 1, 8, 5, 8, 6],
       [1, 2, 3, 6, 1, 2, 2, 7, 7, 2],
       [1, 8, 6, 3, 1, 4, 2, 4, 7, 6],
       [6, 3, 3, 7, 6, 4, 4, 3, 6, 9],
       [8, 9, 7, 7, 7, 6, 8, 9, 4, 2],
       [2, 7, 1, 2, 3, 2, 4, 2, 6, 3],
       [8, 2, 1, 9, 8, 2, 2, 1, 4, 5],
       [2, 6, 1, 2, 8, 4, 4, 2, 4, 4],
       [5, 7, 1, 2, 3, 6, 7, 5, 1, 9],
       [9, 9, 4, 6, 5, 6, 1, 5, 9, 6]])

In [9]:
np.sum(data,axis=1)

array([49, 33, 42, 51, 67, 32, 42, 37, 46, 60])

In [10]:
np.mean(data,axis=1)

array([ 4.9,  3.3,  4.2,  5.1,  6.7,  3.2,  4.2,  3.7,  4.6,  6. ])

In [11]:
np.std(data,axis=1)

array([ 2.11896201,  2.28254244,  2.35796522,  1.92093727,  2.1       ,
        1.83303028,  2.95972972,  2.00249844,  2.61533937,  2.40831892])

In [12]:
np.cos(data)

array([[-0.65364362, -0.41614684,  0.28366219,  0.28366219,  0.28366219,
         0.54030231, -0.14550003,  0.28366219, -0.14550003,  0.96017029],
       [ 0.54030231, -0.41614684, -0.9899925 ,  0.96017029,  0.54030231,
        -0.41614684, -0.41614684,  0.75390225,  0.75390225, -0.41614684],
       [ 0.54030231, -0.14550003,  0.96017029, -0.9899925 ,  0.54030231,
        -0.65364362, -0.41614684, -0.65364362,  0.75390225,  0.96017029],
       [ 0.96017029, -0.9899925 , -0.9899925 ,  0.75390225,  0.96017029,
        -0.65364362, -0.65364362, -0.9899925 ,  0.96017029, -0.91113026],
       [-0.14550003, -0.91113026,  0.75390225,  0.75390225,  0.75390225,
         0.96017029, -0.14550003, -0.91113026, -0.65364362, -0.41614684],
       [-0.41614684,  0.75390225,  0.54030231, -0.41614684, -0.9899925 ,
        -0.41614684, -0.65364362, -0.41614684,  0.96017029, -0.9899925 ],
       [-0.14550003, -0.41614684,  0.54030231, -0.91113026, -0.14550003,
        -0.41614684, -0.41614684,  0.54030231

In [16]:
np.max(data,axis=1)

array([9, 9, 9, 8, 9, 9, 9, 9, 9, 8])

In [13]:
np.argmax(data,axis=1)

array([6, 7, 1, 9, 1, 1, 3, 4, 9, 0], dtype=int64)

In [19]:
data

array([[6, 4, 1, 1, 3, 4, 5, 3, 5, 9],
       [5, 9, 4, 8, 6, 9, 3, 8, 3, 6],
       [7, 9, 9, 2, 4, 6, 5, 9, 8, 2],
       [5, 2, 5, 2, 5, 5, 2, 1, 4, 8],
       [9, 7, 8, 9, 1, 2, 8, 1, 8, 2],
       [8, 7, 8, 9, 7, 6, 9, 3, 5, 7],
       [1, 9, 6, 9, 1, 7, 6, 8, 5, 2],
       [5, 2, 3, 2, 1, 4, 8, 2, 9, 2],
       [1, 9, 9, 6, 1, 8, 7, 6, 5, 9],
       [7, 1, 7, 7, 6, 8, 2, 3, 5, 2]])

In [14]:
np.argsort(data,axis=1)

array([[5, 1, 0, 2, 3, 4, 7, 9, 6, 8],
       [0, 4, 1, 5, 6, 9, 2, 3, 7, 8],
       [0, 4, 6, 3, 5, 7, 2, 9, 8, 1],
       [1, 2, 7, 5, 6, 0, 4, 8, 3, 9],
       [9, 8, 5, 2, 3, 4, 0, 6, 1, 7],
       [2, 0, 3, 5, 7, 4, 9, 6, 8, 1],
       [2, 7, 1, 5, 6, 8, 9, 0, 4, 3],
       [2, 0, 3, 7, 5, 6, 8, 9, 1, 4],
       [2, 8, 3, 4, 0, 7, 5, 1, 6, 9],
       [6, 2, 4, 7, 3, 5, 9, 0, 1, 8]], dtype=int64)

In [21]:
help(np.argwhere)

Help on function argwhere in module numpy.core.numeric:

argwhere(a)
    Find the indices of array elements that are non-zero, grouped by element.
    
    Parameters
    ----------
    a : array_like
        Input data.
    
    Returns
    -------
    index_array : ndarray
        Indices of elements that are non-zero. Indices are grouped by element.
    
    See Also
    --------
    where, nonzero
    
    Notes
    -----
    ``np.argwhere(a)`` is the same as ``np.transpose(np.nonzero(a))``.
    
    The output of ``argwhere`` is not suitable for indexing arrays.
    For this purpose use ``where(a)`` instead.
    
    Examples
    --------
    >>> x = np.arange(6).reshape(2,3)
    >>> x
    array([[0, 1, 2],
           [3, 4, 5]])
    >>> np.argwhere(x>1)
    array([[0, 2],
           [1, 0],
           [1, 1],
           [1, 2]])



In [25]:
np.argwhere((data > 5) & ( data < 7))

array([[0, 0],
       [1, 4],
       [1, 9],
       [2, 5],
       [5, 5],
       [6, 2],
       [6, 6],
       [8, 3],
       [8, 7],
       [9, 4]], dtype=int64)

In [24]:
help(np.argsort)

Help on function argsort in module numpy.core.fromnumeric:

argsort(a, axis=-1, kind='quicksort', order=None)
    Returns the indices that would sort an array.
    
    Perform an indirect sort along the given axis using the algorithm specified
    by the `kind` keyword. It returns an array of indices of the same shape as
    `a` that index data along the given axis in sorted order.
    
    Parameters
    ----------
    a : array_like
        Array to sort.
    axis : int or None, optional
        Axis along which to sort.  The default is -1 (the last axis). If None,
        the flattened array is used.
    kind : {'quicksort', 'mergesort', 'heapsort'}, optional
        Sorting algorithm.
    order : str or list of str, optional
        When `a` is an array with fields defined, this argument specifies
        which fields to compare first, second, etc.  A single field can
        be specified as a string, and not all fields need be specified,
        but unspecified fields will still 