* It's an ensemble method
* Ensamble - Combine different technique to create new technique
* Different order of same data means different decison tree
* Combines different trees to create a forest
* Internally uses multiple decision trees to generate forest

In [1]:
from sklearn.ensemble import RandomForestClassifier

In [2]:
from sklearn.datasets import load_digits

In [9]:
rf = RandomForestClassifier(n_estimators=10, max_depth=6)

In [10]:
digits = load_digits()

In [11]:
from sklearn.model_selection import train_test_split
trainX,testX,trainY,testY = train_test_split(digits.data, digits.target)

In [12]:
rf.fit(trainX,trainY)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=6, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [13]:
rf.score(testX,testY)

0.9111111111111111

In [14]:
rf.score(trainX,trainY)

0.9673348181143281

In [20]:
import numpy as np
np.where(rf.feature_importances_ < .005)

(array([ 0,  1,  7,  8, 11, 14, 15, 16, 17, 18, 23, 24, 31, 32, 35, 39, 40,
        41, 47, 48, 49, 55, 56, 57, 59, 63], dtype=int64),)

In [22]:
from sklearn.datasets import california_housing

In [24]:
housing = california_housing.fetch_california_housing()

In [26]:
housing.data.shape

(20640, 8)

In [27]:
housing.target

array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894])

In [28]:
from sklearn.ensemble import RandomForestRegressor

In [29]:
rfr = RandomForestRegressor(n_estimators=10)

In [32]:
trainX,testX,trainY,testY = train_test_split(housing.data, housing.target)

In [33]:
rfr.fit(trainX, trainY)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [31]:
rfr.feature_importances_

array([0.51796206, 0.05237828, 0.04799802, 0.02911592, 0.03272892,
       0.13530837, 0.09312368, 0.09138474])

In [34]:
rfr.score(testX,testY)

0.777498478311511

In [45]:
hd = housing.data.T[[0,5,6,7]].T

In [46]:
trainX,testX,trainY,testY = train_test_split(hd, housing.target)

In [47]:
rfr = RandomForestRegressor(n_estimators=10)

In [48]:
rfr.fit(trainX,trainY)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [49]:
rfr.score(testX,testY)

0.8111669565694953