* It's an ensemble method
* Ensamble - Combine different technique to create new technique
* Different order of same data means different decison tree
* Combines different trees to create a forest
* Internally uses multiple decision trees to generate forest

In [1]:
from sklearn.ensemble import RandomForestClassifier

In [2]:
from sklearn.datasets import load_digits

In [8]:
rf = RandomForestClassifier(n_estimators=20, max_depth=6)

In [9]:
digits = load_digits()

In [15]:
digits.data.shape

(1797, 64)

In [10]:
from sklearn.model_selection import train_test_split
trainX,testX,trainY,testY = train_test_split(digits.data, digits.target)

In [11]:
rf.fit(trainX,trainY)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=6, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=20, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [12]:
rf.score(testX,testY)

0.9422222222222222

In [13]:
rf.score(trainX,trainY)

0.9725315515961396

In [16]:
rf.feature_importances_

array([0.00000000e+00, 8.77362276e-04, 1.92052227e-02, 9.60928021e-03,
       3.04940854e-03, 2.63090280e-02, 6.62344894e-03, 0.00000000e+00,
       0.00000000e+00, 7.25725051e-03, 4.61994985e-02, 2.88746553e-03,
       1.11567517e-02, 2.09549473e-02, 4.43431261e-03, 0.00000000e+00,
       0.00000000e+00, 8.95605586e-03, 1.79606619e-02, 2.95415374e-02,
       2.86884405e-02, 6.22040701e-02, 3.38837037e-03, 9.36272916e-05,
       0.00000000e+00, 1.83873262e-02, 2.97069001e-02, 1.63249763e-02,
       3.01154190e-02, 1.64949225e-02, 3.98646854e-02, 1.90904019e-04,
       0.00000000e+00, 4.24109891e-02, 2.49113259e-02, 1.41426156e-02,
       5.04234947e-02, 1.88271562e-02, 2.52552868e-02, 0.00000000e+00,
       0.00000000e+00, 9.91808570e-03, 4.38673567e-02, 2.67079813e-02,
       2.51950694e-02, 1.31265598e-02, 3.25602395e-02, 0.00000000e+00,
       0.00000000e+00, 3.58062383e-04, 1.22228564e-02, 1.98134840e-02,
       1.04466454e-02, 2.29580528e-02, 2.89266465e-02, 3.92572475e-03,
      

In [17]:
import numpy as np
np.where(rf.feature_importances_ < .005)

(array([ 0,  1,  4,  7,  8, 11, 14, 15, 16, 22, 23, 24, 31, 32, 39, 40, 47,
        48, 49, 55, 56, 57, 63], dtype=int64),)

In [18]:
from sklearn.datasets import california_housing

In [19]:
housing = california_housing.fetch_california_housing()

In [20]:
housing.data.shape

(20640, 8)

In [21]:
housing.target

array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894])

In [22]:
from sklearn.ensemble import RandomForestRegressor

In [23]:
rfr = RandomForestRegressor(n_estimators=10)

In [24]:
trainX,testX,trainY,testY = train_test_split(housing.data, housing.target)

In [25]:
rfr.fit(trainX, trainY)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [26]:
rfr.feature_importances_

array([0.52768701, 0.05206012, 0.04168619, 0.02876587, 0.03171715,
       0.13632946, 0.09061817, 0.09113602])

In [27]:
rfr.score(testX,testY)

0.7862195485889858

In [55]:
hd = housing.data.T[[0,5,6,7]].T

In [56]:
trainX,testX,trainY,testY = train_test_split(hd, housing.target)

In [57]:
rfr = RandomForestRegressor(n_estimators=10)

In [58]:
rfr.fit(trainX,trainY)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [59]:
rfr.score(testX,testY)

0.7970865142984974

In [61]:
#np.hstack([trainX[:,0].reshape(-1,1),trainX[:,5].reshape(-1,1)])

In [39]:
trainX.shape

(15480, 4)