In [48]:
from sklearn.linear_model import LinearRegression, Ridge, RidgeCV, Lasso, ElasticNet

In [2]:
lr = LinearRegression()

In [30]:
lr.fit([[1,1],[2,2],[3,4]],[1,2,4])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [31]:
lr.coef_

array([  2.09345661e-16,   1.00000000e+00])

In [39]:
reg = RidgeCV(alphas=[.3,.4,.6])

In [40]:
reg.fit([[1,1],[2,2],[3,4]],[1,2,4])

RidgeCV(alphas=[0.3, 0.4, 0.6], cv=None, fit_intercept=True, gcv_mode=None,
    normalize=False, scoring=None, store_cv_values=False)

In [41]:
reg.coef_

array([ 0.37138927,  0.71526823])

In [42]:
reg.alpha_

0.29999999999999999

### Lasso

In [44]:
lasso = Lasso(alpha=.5)

In [45]:
lasso.fit([[1,1],[2,2],[3,3],[4,4]], [1,2,3,4])

Lasso(alpha=0.5, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=False, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False)

In [47]:
import numpy as np
np.round(lasso.coef_,3)

array([ 0.6,  0. ])

In [49]:
en = ElasticNet(alpha=.7)

In [50]:
en.fit([[1,1],[2,2],[3,3],[4,4]], [1,2,3,4])

ElasticNet(alpha=0.7, copy_X=True, fit_intercept=True, l1_ratio=0.5,
      max_iter=1000, normalize=False, positive=False, precompute=False,
      random_state=None, selection='cyclic', tol=0.0001, warm_start=False)

In [51]:
import numpy as np
np.round(en.coef_,3)

array([ 0.316,  0.316])